### ISSUE TITLE
Retrieving extended data doesn't work with serials argument.

### ISSUE THREAD

**Issue by simonrp84** [xoolive/traffic#103]
Hello,
Just to make sure you're keeping busy, a new issue ;-)

I'm trying to retrieve raw messages for particular receivers. As an example:
```
from datetime import datetime, timedelta
from traffic.data import opensky

data = opensky.extended(start=start_time,
                        stop=start_time + timedelta(seconds=1),
                        serials=[80391799, 1806596070] )
```

This produces an error saying that `mintime` is ambiguous. I guess this is because both the `rollcall_replies_data4` table and the `rollcall_replies_data4.sensors.item` array contain `mintime`.

On my local copy of `traffic` I have resolved this by changing line 1073 of `opensky_impala.py` to this:
```        
columns = (table_name + ".mintime, " +
           table_name + ".maxtime, " +
           table_name + ".rawmsg, " + 
           table_name + ".msgcount, " +
           table_name + ".icao24, " +
           table_name + ".hour")
orig_columns = columns
```

And then adding the following on line 1023 (just before `df = self_format_dataframe(df)`):
```
colnames = {}
ocols = orig_columns.split(',')
for col in ocols:
   tcol = col.lstrip().rstrip()
   pos = tcol.find('.')
   colnames[tcol] = tcol[pos+1:]
df.rename(columns=colnames, inplace=True)
```

This works for my particular case, but I do not know if this will break some other use of `traffic`, and it is also maybe not so elegant. Therefore I raise an issue rather than making a PR.
If the above changes are OK to you then I'll make a PR instead, otherwise I can leave it to you to determine the best solution :-)

**Comment by xoolive** [comment]
I tried (almost) your changes but it breaks the tests indeed (see `tests/test_impala.py` with pytest). I don't have much time these days to investigate though, but I'll come to it when I get a spare minute... 🕙

**Comment by MatthiasPoppe** [comment]
@simonrp84, @xoolive: recently I could not retrieve any EHS messages. Instead, I only got ADS-B messages by calling query_ehs() without any notification or error message (using traffic version 2.5). To verify it, I tried an example from the documentation:

flight = opensky.history(
    "2018-06-11 15:00",
    "2018-06-11 17:00",
    callsign='KLM1308',
    count=True,
    return_flight=True
)
ehs_flight = (
    flight
    # this triggers a new specific call to OpenSky Impala
    .query_ehs()
    # avoid big gaps in angle
    .unwrap()
    # cascade of median filters
    .filter()
    #.filter(groundspeed=53, tas=53, ias=53, heading=53, track=53)
)

Last line was commented out to avoid error message. ehs_flight only contains ADS-B information, no Mode S EHS data at all (e.g. no IAS, TAS, heading etc). Not sure whether this is related to the bug described by Simon. The workaround did not help in my case although I am not sure about the indicated line numbers.

**Comment by xoolive** [comment]
Hello @MatthiasPoppe 
It seems OpenSky database went through some storage issues and had to delete some of this data. They are working on it and on my side I will have to update examples from the documentation...

**Comment by MatthiasPoppe** [comment]
Thanks for your update. Cross fingers that OpenSky guys can solve the problem and that there is no loss of data...
