### ISSUE TITLE
Opensky problem

### ISSUE THREAD

**Issue by Tukaric** [xoolive/traffic#104]
Hello,

I've installed Anaconda and traffic. Trying to follow your examples here 

https://traffic-viz.readthedocs.io/en/latest/opensky_impala.html#examples-of-requests 

returns 

AttributeError: module 'traffic.data.adsb.opensky' has no attribute 'extended'

Same thing happens with 'history'. I am new to this and there may be a simple solution, but I am unable to find it.

Thank you for any help you may provide!

**Comment by xoolive** [comment]
Thank you for your interest in the library.
I clarified the page you are referring to, the web page should be up to date within 15 minutes.

Just do:
```python
from traffic.data import opensky
```
