### ISSUE TITLE
Importing data using traffic.core.Traffic.from_file() assigns object dtype to time variables

### ISSUE THREAD

**Issue by jaimebw** [xoolive/traffic#105]
Hello Mr.Olive,
So I am not sure if this is a bug or it is expected. When I save the downloaded data from the OpenSky Impala Shell from a couple of days, and I import it again with Traffic.from_file(), the dtypes from the time variables are changed to objects. This is easy to change by using pandas, but I dont think this is the expected behaviour.
This is ```df.data.info()``` after the download.
<img width="647" alt="Captura de pantalla 2020-10-13 a las 12 56 50" src="https://user-images.githubusercontent.com/22820466/95852143-9220c580-0d53-11eb-869e-bae4212376af.png">
This is ```df.data.info()``` after importing the saved .csv
<img width="540" alt="Captura de pantalla 2020-10-13 a las 12 58 27" src="https://user-images.githubusercontent.com/22820466/95852276-cac09f00-0d53-11eb-87c9-bd06d0de3db2.png">
The code used is:
```python
from traffic.data import opensky
from traffic.data import eurofirs

flight = opensky.history(
    "2019-06-20",
    "2019-06-21",    
    bounds= eurofirs['LSAS'] 
)
flight.data.info()
flight.to_csv("example.csv")


from traffic.core import Traffic
flight = Traffic.from_file("example.csv")
flight.data.info()
``` 
PS: thanks for the library, I use it on a daily basis for my research!!

**Comment by xoolive** [comment]
Pleas try with the following options:

```python
flight = Traffic.from_file("example.csv", parse_dates=['timestamp', 'hour', 'last_position'])
```

Also I do not recommend using csv as a pivot format, see [here](https://traffic-viz.github.io/export.html)

**Comment by jaimebw** [comment]
Works perfectly, thanks for you time!
