### ISSUE TITLE
Adding a request debug option in the rawdata, history ... methods in opensky_impala.py

### ISSUE THREAD

**Issue by Wirden** [xoolive/traffic#106]
Hi Xavier,

I was thinking that it would be interesting to have a boolean parameter like **display_request**  to print in the command line the final request sent to Opensky to debug eventual non-desired results in all request building methods of opensky_impala.py. I don't want to create a PR for 2 lines but I could if you prefer.

Something like: 
`if debug: print(request)` just before calling : `df = self._impala(request, columns=parse_columns, cached=cached)`

What do you think ?
Regards,
Antoine

**Comment by xoolive** [comment]
How about activating INFO logging messages?

There is a shortcut going as follows:
```python
from traffic.core import loglevel
loglevel('INFO')
```

**Comment by Wirden** [comment]
Oh well that works like a charm !  :ok_hand:
Closing then.
Thank you !
