### ISSUE TITLE
Is it possible to filter existing Traffic objects with nm_airspaces bounds?

### ISSUE THREAD

**Issue by jaimebw** [xoolive/traffic#107]
Hello Mr.Olive,
I was wondering if it is possible to filter existing Traffic objects downloaded from OpenSky Impala Shell using a nm_airspace as the bound. Is it possible to do it directly through Traffic, or I would need to use other libraries like Shapely? 
Thanks in advance.

**Comment by xoolive** [comment]
Hello Jaime,

You may have a look at Flight.clip() and Flight.inside_bbox() methods. 

If you prefer clip, perform inside_bbox first if you have a lot of flights to perform as the second one is a much faster option...

**Comment by jaimebw** [comment]
Flight.inside_bbox() worked perfectly. Thank you very much!
