### ISSUE TITLE
Retrieving opensky history hangs

### ISSUE THREAD

**Issue by simonrp84** [xoolive/traffic#11]
Trying to load data via the opensky/hadoop method causes traffic to hang.
I run this command: flight = opensky.history("2017-02-05", callsign="EZY158T")

And I see:
  0%|                        | 0/24 [00:00<?, ?it/s]

This display stays on the screen forever (or, at least for the 2 hours I left it!) and the data never downloads.
Any ideas?

**Comment by xoolive** [comment]
Mmmmh I cannot reproduce the error here :disappointed: 

```
>>> from traffic.data import opensky
>>> opensky.history("2017-02-05", callsign="EZY158T")
 67%|████████████████████████████▋              | 16/24 [00:40<00:29,  3.63s/it]
```

Can you activate the DEBUG messages and try again?
```
>>> from traffic.core.logging import loglevel
>>> loglevel('DEBUG')
```

**Comment by xoolive** [comment]
Also can you ensure you are on the `HEAD` on `master`. Your latest contribution/bugfix is not released (yet) in the pip-installable package.

**Comment by simonrp84** [comment]
It works now. I made no changes so I don't know what happened, maybe a temporary problem with the opensky server. I will close this now!
