### ISSUE TITLE
Cannot install Traffic package

### ISSUE THREAD

**Issue by sarahboufelja** [xoolive/traffic#114]
Hi I have an issue when installing Traffic package, the pip install traffic terminates with the following error:
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/58/v83jx2591k13sd8mgxxs7pz00000gn/T/pip-install-ff_ycfrc/Cartopy/

The issue seems with Cartopy. I installed Shapely and Cartopy beforehand with a pip install shapely and conda install --channel conda-forge cartopy, 
But when installing the Traffic package, it does not work, 
Python version : 3.6

**Comment by xoolive** [comment]
Hello Sarah, I am not very familiar with this error, but I recommend that you uninstall shapely and cartopy before reinstalling with `conda install` (see the warning box [here](https://traffic-viz.github.io/installation.html)). This is the safest option that "always" work.
