### ISSUE TITLE
Issues installing traffic on latest versions of Jupyter Lab

### ISSUE THREAD

**Issue by jaimebw** [xoolive/traffic#115]
I have had some trouble recently trying to install the library on my computer. I think the issue was that I was trying to run it with the latest version of Jupyter Lab and some libraries were trying to use deprecated packages. I was able to solve this problem by using an older version of Jupyter Lab.
It could be interesting to add this to the troubleshooting section in the documentation of the library, if you want I can send a pull request explaining the issue and the way I think it can be solved. By the way, I am using a Macbook Pro 2019 with macOS Big Sur

**Comment by xoolive** [comment]
Sure any insight is welcome, thank you!

From what I understand, I'm just wondering whether this could be silently fixed by adding/updating version numbers in the dependencies of the setup.py but I'll let you submit whatever you think is best. It's always possible to update afterwards

**Comment by jaimebw** [comment]
Ive been looking again and I think that the issue wasn't because of Jupyter Lab, but because of the version of Python I had previously installed. Ive been doing some tests and I found out that it didn't work before because I previously installed pandas which used Python 3.8.5 and some of the libraries that traffic needs dont work with that version of Python. 
Maybe it could be useful to add  that its necessary to create and virtualenv from cero in Anaconda/miniconda and then run the commands as stated as in the installation instructions . I have created a pull request with a little modification.

**Comment by xoolive** [comment]
I really should create a conda target... This would cut the number of issues by half I guess 😅

**Comment by jaimebw** [comment]
Yeah, that would be a really cool improvement. From my perspective, users of the library(the ones I know) aren't too keen with Python and these kind of things are really frustrating for newbies.

**Comment by xoolive** [comment]
Is it too late to ask for "time" to 🎅 ?

**Comment by jaimebw** [comment]
Maybe not hahahaha, but I wouldnt mind helping with this(creating the conda target) if you want. Ive never done it before, but I hope its not too different from the pip one. Happy Christmas btw!

**Comment by xoolive** [comment]
Same here, I have to look into this. It shouldn't be too complicated and I would appreciate the help but maybe it's easier if it's all registered with the same name/account though.

**Comment by xoolive** [comment]
I'll try that asap: https://conda-forge.org/#add_recipe

**Comment by jaimebw** [comment]
Looks nice, when you finish the implementation, Ill try it.

**Comment by xoolive** [comment]
🏗️

**Comment by xoolive** [comment]
@jaimebw just fyi, all dependencies must also be packaged by conda-forge. There were three missing which I submitted. One of them is now packaged. When the two others are accepted I can submit the recipe for traffic 😪

**Comment by jaimebw** [comment]
Looking forward to it 😉

**Comment by xoolive** [comment]
Sorry bad news, https://github.com/conda-forge/staged-recipes/pull/13649
Next version of pyModeS will be without this dependency, so I will only package version 2.6 with conda. But it's all ready here, so it will be there for sure!

**Comment by jaimebw** [comment]
Perfect 👌 , Im closing the issue then.
