### ISSUE TITLE
"Is that a plane?" case gives "AttributeError"

### ISSUE THREAD

**Issue by ElSabio97** [xoolive/traffic#121]
Hi xoolive!

I'm trying to follow this case the documentation covers (https://traffic-viz.github.io/scenarios/is_this_a_plane.html).

The problem shows up when the program calls the StateVectors to get the bounds and set the variable "around":

```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-b7fb620556b3> in <module>
     12 
     13 around = opensky.history(
---> 14     p.name - timedelta(minutes=5),
     15     p.name + timedelta(minutes=5),
     16     bounds=(

AttributeError: 'StateVectors' object has no attribute 'name'
```
I wanted to follow this: https://stackoverflow.com/questions/62982542/type-object-has-no-attribute-name, to solve it, but I don't feel it is the same issue.

Also when calling "p", I see it gives many data (callsing, latitude, longitude, etc). But when I call, for instance, "p.callsign", it gives me again the same Error:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-3-9da02a7a8ea6> in <module>
----> 1 p.callsign

AttributeError: 'StateVectors' object has no attribute 'callsign'
```
But clearly the object has callsign as an attribute since:
![image](https://user-images.githubusercontent.com/40704074/111278937-6e331a00-863a-11eb-8235-d8f4a6caafbe.png)

Also this DeprecationWarning shows up:

```
C:\Users\Shadow\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
```

But I don't believe this is the root of the issue.

Thank you for your amazing work!

**Comment by xoolive** [comment]
Sorry the documentation was outdated. Can you try again now? (well in a few minutes after the documentation is updated online!)

**Comment by ElSabio97** [comment]
It works perfectly fine!

Thank you!!!
