### ISSUE TITLE
Document working examples start-to-finish to ease on-boarding

### ISSUE THREAD

**Issue by espinielli** [xoolive/traffic#128]
I am studying `traffic` and tried to use it in some *basic* use cases, but got slapped in my face 😬 

I am proposing few scenarios that could be documented to enhance on-boarding of new users:
- detection of go-around's
- detection of landing runway
- detection top-of-climb/-descent
 
The idea is to present the full cycle:
1. data extraction from OSN
2. eventual cleaning (?) / tips for survival
3. detection
4. eventual visualization

I started with the first one but as said I got stuck without a clue to what can be done to unblock the analysis.
Here is how it started (from latest on master on Github), with step 1. and 3. for the go-around's use case:

```python
from traffic.data import opensky
# 1. extract data from OSN (and filter + resample)
landings_eham = opensky.history(
    "2020-01-02 00:00",
    "2020-01-03 00:00", 
    arrival_airport = 'EHAM'
).filter().resample('1s')
landings_eham = landings_eham.eval()

# 3. detect go-around's
go_arounds_eham = landings_eham.has("go_around").eval(
    desc="go_around", max_workers=4
)
```
and here how it failed (without much hunches for me to guess what to do next):

```text
Traceback (most recent call last):
 ...
  File ".../traffic/algorithms/navigation.py", line 356, in aligned_on_ils
    if _airport is None or _airport.runways.shape.is_empty:
AttributeError: 'NoneType' object has no attribute 'shape'
"""
```

**Comment by espinielli** [comment]
Here is what worked (thanks Xavier for the help off-line):

```python
from traffic.data import airports
from traffic.data import opensky

airport = airports["EHAM"]

# 1. extract data from OSN:
#   - keep the flights that are (guessed to be) landing to the relevant airport
#   - filter and resample
landings_eham = opensky.history(
    "2020-01-02 18:00",
    "2020-01-02 19:00", 
    arrival_airport = airport.icao) \
    .landing_at(airport.icao) \
    .filter() \
    .resample('1s')

# 2. detect go-around's
go_arounds_eham = landings_eham \
    .all("go_around").eval(
        desc="go_around",
         max_workers=8)
```

The `landing_at(airport.icao)` proved to be critical to filter out trajectories with not good enough coverage.

**Comment by espinielli** [comment]
Note: if `resample('1s')` is omitted the `go_around` detection fails.
How do we document the need to use `resample`? Does it has to be mandatory for certain usages? Which ones?

**Comment by xoolive** [comment]
Thank you @espinielli for mentioning the issue.
Indeed a "navigation" documentation page is on my plate (so leaving the issue open), but any help is welcome!

The bug you mention is now fixed by 60438a8

**Comment by espinielli** [comment]
So simplifying even further (and using the above fix):
* no need to `resample`
* no need to pre-filter on `landing_at`
* explicitly specify the go-around airport you are interested in

```python
# Stay within 40 nmi of the airport
tma_landings_eham = opensky.history(
    "2020-01-03 08:00",
    "2020-01-03 09:00", 
    arrival_airport = airport.icao) \
    .distance(airport).query('distance < 40') \
    .filter() \
    .eval()
tma_go_arounds_eham = tma_landings_eham \
    .all(lambda f: f.go_around(airport)).eval(
        desc="go_around",
         max_workers=1)
```

**Comment by kovar-ursa** [comment]
Another welcome example would show how to open the initial authenticated connection to opensky. For example, if I try to use:

```flight = opensky.history(
    "2017-02-05",
    # stop is implicit, i.e. stop="2017-02-06"
    callsign="EZY158T",
    return_flight=True
)```

I get:

NameError: name 'opensky' is not defined

I suspect `opensky` is my connection but what call creates it?

**Comment by kovar-ursa** [comment]
I did that and still get the authentication error.

```
## This file contains configuration information for the Python traffic library
##   Documentation page: https://traffic-viz.github.io/
##   Github repository: https://github.com/xoolive/traffic

## Lines prefixed by a # are commented.
## Lines prefixed by a double ## are documentation.

[global]

## aixm_path and nm_path refer to two sources of aeronautical information
## provided by Eurocontrol. Data is updated every AIRAC cycle.
## https://traffic-viz.github.io/airac_usage.html

aixm_path =
nm_path =

[opensky]

## Input here your credentials for accessing the OpenSky Impala shell
## https://opensky-network.org/impala-guide

username = dkovar
password = masked
"~/Library/Application Support/traffic/traffic.conf" 81L, 2589C
```

**Comment by xoolive** [comment]
Can you access the service with the regular ssh command?

**Comment by kovar-ursa** [comment]
I can access it through the HTTP API and through ssh.

```
ssh -p 2230 -l name data.opensky-network.org  
name@data.opensky-network.org's password: 
Starting Impala Shell without Kerberos authentication
***********************************************************************************
OpenSky Network Impala Shell
***********************************************************************************
[hadoop-29:21000] > 
```

**Comment by xoolive** [comment]
Apart from a typo in your password, I have no idea...
I am sorry but it seems this is the only problem that is impossible to fix without access to your machine.

**Comment by kovar-ursa** [comment]
OK, I'll sort it out and update this ticket. Thank you!

**Comment by kovar-ursa** [comment]
Greetings,

I found the error message in opensky_impala.py. That module implements an Impala class which, if initialized, gets the username and password.

Is there any documentation on how to use that class?

I think that is my missing piece of documentation that unlocks most everything else.

-David

**Comment by espinielli** [comment]
Check the docs on config.
https://traffic-viz.github.io/opensky_impala.html

**Comment by kovar-ursa** [comment]
Greetings,
Thank you very much, I'm not sure how I failed to find that.
-David

**Comment by espinielli** [comment]
Now a new world opens up: do not refrain to ask for help / support.
FYI there is also a gitter channel for "interacting" with like-minded users of traffic
https://gitter.im/xoolive/traffic
