### ISSUE TITLE
Different number of unique aircraft returned by opensky impala and traffic impala

### ISSUE THREAD

**Issue by simonrp84** [xoolive/traffic#13]
Hi again,
I am looking at some historical data and see a different number of unique icao24 registrations between traffic and impala.
Here's what I do in traffic:
```
from traffic.data import opensky
from datetime import datetime
bounds   =  (-74.7,40.3,-72.9,41.2)
start_dt =  datetime(2019,2,28,17,0)
end_dt   =  datetime(2019,2,28,18,0)
flights = opensky.history(start=start_dt,stop=end_dt, bounds=bounds)
print('Number of unique icao24:  ',flights.data['icao24'].nunique())
```
Which gives: `Number of unique icao24:   133`

But if I run this query in impala:
```SELECT COUNT(DISTINCT icao24) FROM state_vectors_data4 WHERE time>=1551373200 AND time<=1551376800 AND hour>=1551373200 AND hour<=1551376800 AND lat>=40.3 AND lat<=41.2 AND lon>=-74.7 AND lon<=-72.9;```
I get: 
```
+------------------------+
| count(distinct icao24) |
+------------------------+
| 319                    |
+------------------------+
```

So impala is returning around 2.4 times more unique icao24 addresses than traffic.

Is traffic doing some pre-filtering to this data to remove bad position reports, or have I misunderstood how something works? :)

**Comment by xoolive** [comment]
Can you try again with `opensky.history(..., cached=False)`?

Since the request calls for very recent data, things may have changed in the db since your first call.

**Comment by simonrp84** [comment]
Thank you Xavier, I must have been unlucky in my timing and downloaded the data just before the db updated! Traffic now also shows 319 unique icao24s
Closing this issue.

**Comment by xoolive** [comment]
By the way, you can pass a handmade query to `opensky._impala("select ...")` when you want to debug things.
