### ISSUE TITLE
Obtain ADS-B raw data from Opensky

### ISSUE THREAD

**Issue by ChenhuiAn-git** [xoolive/traffic#137]
Hello.
I recently need to download the raw data of ADS-B from Opensky. I checked the documentation and did not find a way to obtain the raw data of ADS-B. Would you consider adding this part of the content? 
Many thanks.

**Comment by xoolive** [comment]
Hello Chenhui,
Is the following section not enough?
https://traffic-viz.github.io/opensky_impala.html#requests-for-raw-data

Xavier

**Comment by ChenhuiAn-git** [comment]
> 晨辉你好，
> 下面的部分还不够吗？
> https://traffic-viz.github.io/opensky_impala.html#requests-for-raw-data

Thank you for your reply. The problem has been solved.
