### ISSUE TITLE
Using "landing configurations" example on a particular airport does not work

### ISSUE THREAD

**Issue by ElSabio97** [xoolive/traffic#140]
I am trying to use `landing configurations` example on Madrid and this is what I'm running:

```
from traffic.data import opensky, airports
import altair as alt

airport = airports['LEMD']
vuelo = opensky.history(
    start="2021-05-15 00:00",
    stop="2021-05-16 00:00",
    arrival_airport=airport.icao
)

stats = (
    vuelo.all("aligned_on_LEMD")
    .eval(desc="", max_workers=8)
    .rename(columns=dict(flight_id="old_flight_id"))
    .summary(["old_flight_id_max", "stop", "ILS_max"])
    .query("stop.dt.month == 10")
    .rename(columns=dict(ILS_max="ILS", old_flight_id_max="flight_id"))
    .sort_values("stop")
)
```
An error comes up after the download is complete:

`AttributeError: 'Flight' has no attribute 'old_flight_id_max'`

I think this is caused because `landing_zurich_2019` has attributes `vuelo` does not have. But I believed they have the same structure because I think `landing_zurich_2019`  was created with an `opensky.history` query like every other `state_vectors` dataframe.

**Comment by xoolive** [comment]
You need to assign `flight_id` to your dataset first.
Try `vuelo.assign_id().all("aligned_on_LEMD")...`

**Comment by ElSabio97** [comment]
> You need to assign `flight_id` to your dataset first.
> Try `vuelo.assign_id().all("aligned_on_LEMD")...`

This creates a figure but somehow it does not create a proper figure. This is the output "figure":
![visualization (5)](https://user-images.githubusercontent.com/40704074/122474084-01c21100-cfc3-11eb-964c-7b207868f9c8.png)
