### ISSUE TITLE
Documentation is partly gone

### ISSUE THREAD

**Issue by sfo** [xoolive/traffic#147]
Since some day during the last week, parts of the documentation are gone, e.g. [Flight](https://traffic-viz.github.io/traffic.core.flight.html), [Traffic](https://traffic-viz.github.io/traffic.core.traffic.html), [Airspace](https://traffic-viz.github.io/traffic.core.airspace.html), and [FlightIterator](https://traffic-viz.github.io/traffic.core.iterator.html) in the [Core structure](https://traffic-viz.github.io/core_structure.html) are basically empty.

**Comment by xoolive** [comment]
Hello @sfo, thanks for raising this up.
I found the bug yesterday evening, I just need the time to fix it now :wink: 

For reference, it appears here:
https://github.com/xoolive/traffic/runs/3065248608?check_suite_focus=true#step:7:100

Maybe a type annotation on `pd.__version__` could help, but I am not sure about it.

**Comment by xoolive** [comment]
It's back with 4dbb0ad :smiley: 
cc @junzis
