### ISSUE TITLE
`Flight.clip()` cuts off last record of trajectory if trajectory ends within shape

### ISSUE THREAD

**Issue by sfo** [xoolive/traffic#150]
When a trajectory ends within a shape that is used for clipping the trajectory (e.g. clipping an approach trajectory to an approach sector), the trajectory will lose the last record. The reason seems to be that `clip()` and `clip_iterate()` call `between()` with `strict` defaulting to `True`, which in turn leads to filtering of records by condition `"@start < timestamp < @stop"` and thus excluding the last point of the trajectory, regardless if its location is within the shape or not.

This issue likely also applies to the other way around: loosing start of trajectory that starts within the shape.

Maybe the solution could be to have a `strict` parameter in `clip()` and `clip_iterate()` as well, possibly even something like `strict_start` and `strict_end`. However, I hardly can oversee the side effects or other edge cases, this change could have.

**Comment by xoolive** [comment]
Indeed, we should probably add the `strict=True` flag on https://github.com/xoolive/traffic/blob/0f5d629cc6b79b7a5d8897563d36b6e980b7299e/traffic/core/flight.py#L1986 and https://github.com/xoolive/traffic/blob/0f5d629cc6b79b7a5d8897563d36b6e980b7299e/traffic/core/flight.py#L2018

Do you want to try it on your code and file a PR if it fixes your issue?

**Comment by sfo** [comment]
Sorry for the delay, I had some problems with the pre-commit hook yesterday but no time to fix it (false positive type error in pkcs12, btw).
I just uploaded the changes that I tested with my application code.

The advantage would be that behavior in existing code does not change when changing the method signatures as proposed.

**Comment by xoolive** [comment]
Thank you @sfo, could you start a pull request so I can merge your correction?
