### ISSUE TITLE
historical data with `airport` and `serials` fails

### ISSUE THREAD

**Issue by espinielli** [xoolive/traffic#154]
I am trying to extract historical data for Stockholm airport (ESSA) as seen by a specific sensor (installed yesterday 2021-08-17).

The following fails 
```python
t = opensky.history(
    start = "2021-08-18 08:00:00",
    stop  = "2021-08-18 09:00:00",
    airport = 'ESSA',
    serials = -1408232560
)
```
with the following stack trace (enabling logging as per bug submission instructions hasn't added more info)
```
ImpalaError: time	icao24	lat	lon	velocity	heading	vertrate	callsign	onground	alert	spi	squawk	baroaltitude	geoaltitude	lastposupdate	lastcontact	hour	firstseen	origin	lastseen	destination	day
select sv.time, sv.icao24, sv.lat, sv.lon, sv.velocity, sv.he
eading, sv.vertrate, sv.callsign, sv.onground, sv.alert, sv.spi, sv.squawk, sv.ba
aroaltitude, sv.geoaltitude, sv.lastposupdate, sv.lastcontact, sv.hour, est.first
tseen, est.estdepartureairport, est.lastseen, est.estarrivalairport, est.day from
m state_vectors_data4 , state_vectors_data4.serials s as sv join (select icao24 a
as e_icao24, firstseen, estdepartureairport, lastseen, estarrivalairport, callsig
gn as e_callsign, day from flights_data4 where (estdepartureairport ='ESSA' or es
starrivalairport = 'ESSA') and (1629244800 <= day and day <= 1629331200)) as est 
 on sv.icao24 = est.e_icao24 and sv.callsign = est.e_callsign and est.firstseen <
<= sv.time and sv.time <= est.lastseen where hour>=1629273600.0 and hour<16292772
200.0 and time>=1629273600.0 and time<1629277200.0 and s.ITEM = -1408232560 ;
ERROR: AnalysisException: Syntax error in line 1:
...e_vectors_data4.serials s as sv join (select icao24 as...
                             ^
Encountered: AS
Expected: CROSS, FROM, FULL, GROUP, HAVING, INNER, JOIN, LEFT, LIMIT, OFFSET, ON, ORDER, RIGHT, STRAIGHT_JOIN, TABLESAMPLE, UNION, USING, WHERE, COMMA

CAUSED BY: Exception: Syntax error

---------------------------------------------------------------------------
ImpalaError                               Traceback (most recent call last)
~/kaos/cucu.py in 
----> 80 t = opensky.history(
      81     start = "2021-08-18 08:00:00",
      82     stop  = "2021-08-18 09:00:00",
      83     airport = 'ESSA',
      84     serials = -1408232560

/usr/local/Caskroom/miniconda/4.6.14/miniconda3/envs/traffic/lib/python3.9/site-packages/traffic/data/adsb/opensky_impala.py in history(self, start, stop, date_delta, return_flight, callsign, icao24, serials, bounds, departure_airport, arrival_airport, airport, count, cached, limit, other_tables, other_params, nautical_units, progressbar, *args)
    924             )
    925 
--> 926             df = self._impala(request, columns=parse_columns, cached=cached)
    927 
    928             if df is None:

/usr/local/Caskroom/miniconda/4.6.14/miniconda3/envs/traffic/lib/python3.9/site-packages/traffic/data/adsb/opensky_impala.py in _impala(self, request, columns, cached)
    296             logging.info("Closing {}".format(cachename))
    297 
--> 298         return self._read_cache(cachename)
    299 
    300     @staticmethod

/usr/local/Caskroom/miniconda/4.6.14/miniconda3/envs/traffic/lib/python3.9/site-packages/traffic/data/adsb/opensky_impala.py in _read_cache(cachename)
    163         if error_msg is not None:
    164             cachename.unlink()
--> 165             raise ImpalaError(error_msg)
    166 
    167         return None

ImpalaError: time	icao24	lat	lon	velocity	heading	vertrate	callsign	onground	alert	spi	squawk	baroaltitude	geoaltitude	lastposupdate	lastcontact	hour	firstseen	origin	lastseen	destination	day
select sv.time, sv.icao24, sv.lat, sv.lon, sv.velocity, sv.he
eading, sv.vertrate, sv.callsign, sv.onground, sv.alert, sv.spi, sv.squawk, sv.ba
aroaltitude, sv.geoaltitude, sv.lastposupdate, sv.lastcontact, sv.hour, est.first
tseen, est.estdepartureairport, est.lastseen, est.estarrivalairport, est.day from
m state_vectors_data4 , state_vectors_data4.serials s as sv join (select icao24 a
as e_icao24, firstseen, estdepartureairport, lastseen, estarrivalairport, callsig
gn as e_callsign, day from flights_data4 where (estdepartureairport ='ESSA' or es
starrivalairport = 'ESSA') and (1629244800 <= day and day <= 1629331200)) as est 
 on sv.icao24 = est.e_icao24 and sv.callsign = est.e_callsign and est.firstseen <
<= sv.time and sv.time <= est.lastseen where hour>=1629273600.0 and hour<16292772
200.0 and time>=1629273600.0 and time<1629277200.0 and s.ITEM = -1408232560 ;
ERROR: AnalysisException: Syntax error in line 1:
...e_vectors_data4.serials s as sv join (select icao24 as...
                             ^
Encountered: AS
Expected: CROSS, FROM, FULL, GROUP, HAVING, INNER, JOIN, LEFT, LIMIT, OFFSET, ON, ORDER, RIGHT, STRAIGHT_JOIN, TABLESAMPLE, UNION, USING, WHERE, COMMA

CAUSED BY: Exception: Syntax error
```

It works if I take out the `airport` argument
```python
t = opensky.history(
    start = "2021-08-18 08:00:00",
    stop  = "2021-08-18 09:00:00",
    serials = -1408232560
)
t
```

![Screen Shot 2021-08-18 at 17 44 25](https://user-images.githubusercontent.com/891692/129929311-afa148ed-fa01-4e32-b226-7a66a2150067.png)

If I just ask for for the flights at ESSA (not necessarily from the sensor of interest)

```python
t = opensky.history(
    start = "2021-08-10 08:00:00",
    stop  = "2021-08-10 09:00:00",
    airport = 'ESSA'
)
t
```
things work but I get `None` il terms of flights: I guess this is because the flight table, `flight_table_data4`, has not yet been populated...(if I try with EGLL [same time interval] it return nothing too, but if I go back to Aug 10 2021 I get a list of flights back)

**Comment by xoolive** [comment]
Thank you for the bug report.

I think we reach the limits of this type of hand-made query generation methods.
Actually I am not sure what's best:

1. first just raise an Exception to say this combination is not supported;
2. think about all possible combinations of parameters and ensure generated requests are all valid, then be extra wary if we add one more parameter;
3. reengineer the whole query generation to something more robust.

I have long thought option 3 is best albeit overkill, but maybe it's not that overkill after all. Going beyond option 1 is unfortunately not a priority at the moment but help is welcome.

Any insight @junzis ?

**Comment by xoolive** [comment]
Related issue #103 (closed but still valid)

**Comment by espinielli** [comment]
Xavier, I do not dispute the analysis above and the willingness to refactor the impala queries part of the code base.

BUT there could be still a *quick* fix to this issue.

The issue at hand is caused by `as sv` being added in the wrong place in the query.
Maybe instead of handling the aliasing of the `state_vector_data4` table as `sv` conditionally, the alias could be always in place...
This would eliminate to have to add the `sv.` prefix to the columns conditionally on the `Impala.history()` parameters (i.e. `airport`, `departure_airport`, `arrival_airport`, ...) and eliminate quite some *tedious* logic in the code.

What do you think? Does it make sense or am I missing some (more hidden than the code I read) tar pit?

**Comment by wtroisey** [comment]
Hi I encounter the same issue when filtering by `departure_airport` and `arrival_airport` and start and end datetimes.

This would be great functionality and I'm wondering if this is easy to add to the otherwise great module.

**Comment by espinielli** [comment]
@wtroisey could you please report the installed version number of traffic and the code that you executed, together with the error?

**Comment by wtroisey** [comment]
```traffic == 2.5
Python 3.7
Linux Mint 20.2
```

```python
from traffic.data import opensky

flights = opensky.history(
    datetime(2020, 8, 24), 
    datetime(2020, 8, 25),
    icao24='######'
)
print(flights)    # None
```

No warnings or errors

**Comment by espinielli** [comment]
@wtroisey you need at least 2.6.5 to have the `departure_airport` and `arrival_airport` work.
Please upgrade to it (or even better the latest one) and let us know whether the issue is still there.

**Comment by wtroisey** [comment]
Ok thanks for the response, apparently traffic requires `python >= 3.7.1`. I am currently running 3.6.9. Running `pip install` with `--no-deps` or `--ignore-reqires-python` do not correct this. Why does the package require this Python version?

**Comment by espinielli** [comment]
dependencies on other functionality

**Comment by wtroisey** [comment]
Closed, thanks for the help
