### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by johnfitzy** [xoolive/traffic#159]
Hello. 

There seems to be a dependency issue with _cartes_ and _pyopenssl_. I noticed that _cartes_ was updated to 0.4 a few days ago however this doesn't seem to be reflected in the Conda package _traffic 2.6.4_. Conda itself seems to be using _pyopenssl_ 21.0.0 now.

To recreate:

Fresh environment with Docker image jupyter/minimal-notebook:latest

Then:

```
conda config --set channel_priority strict
conda config --add channels conda-forge
conda create -n traffic -c conda-forge python=3.9 traffic
conda update -n traffic -c conda-forge traffic
```

Then two errors are thrown when trying to import traffic:

pkg_resources.VersionConflict: (cartes 0.4 (/opt/conda/envs/traffic/lib/python3.9/site-packages), Requirement.parse('cartes<0.4,>=0.3'))

pkg_resources.VersionConflict: (pyOpenSSL 21.0.0 (/opt/conda/envs/traffic/lib/python3.9/site-packages), Requirement.parse('pyOpenSSL<21.0,>=20.0'))

Both are solved by installing _cartes 0.3_ and _pyopenssl 20.0.1_

Thanks.

**Comment by xoolive** [comment]
Thank you,

I'm aware of many such dependency issues.

Switching to poetry to manage dependencies and not being as strict with conda definitions created this mess when new versions of dependencies are released indeed. 

The only way out of this I can see is probably to do a new release. I'll try in the coming days, maybe next week. 

In the meantime, git clone and pip install . should clear most of the mess.

**Comment by johnfitzy** [comment]
OK thanks.

**Comment by xoolive** [comment]
Just for reference for myself about dependency version numbers:
https://python-poetry.org/docs/dependency-specification/#caret-requirements

**Comment by xoolive** [comment]
The new recipe, together with new release, should be ok.
https://github.com/conda-forge/traffic-feedstock/pull/5

**Comment by johnfitzy** [comment]
I can confirm it is now working. Thanks.
