### ISSUE TITLE
Airport runway label slightly not perpendicular to runway

### ISSUE THREAD

**Issue by espinielli** [xoolive/traffic#166]
I noticed that runway id labels are slightly not perpendicular with respect to the relevant runway.
For example take the following code:

```python
import matplotlib.pyplot as plt
from cartes.crs import EuroPP

fig, ax = plt.subplots(figsize=(8, 8), subplot_kw=dict(projection=EuroPP()))
airports['LFBO'].plot(ax, runways=dict(color='red'), labels=dict(fontsize=12)) 
ax.spines['geo'].set_visible(False)
```
which results in
![lfbo](https://user-images.githubusercontent.com/891692/142759056-ae9ddc77-ab44-4ba2-8559-2364b631b936.png)

It looks to me that the runway labels are not really perpendicular to the runway direction.
Looking at the code for ingesting the runway information, I was wondering whether it would make a difference to use directly `le_heading_degT` and `he_heading_degT` from the OurAirports dataset rather than calculating the threshold bearing as in [lines 237-240](https://github.com/xoolive/traffic/blob/ef0edf00c693bc0db111952fa9638e0031aa499f/traffic/data/basic/runways.py#L237-#L240) which could be the source of the little misalignment.

In [OurAirports](https://ourairports.com/help/data-dictionary.html) `le_heading_degT` (and similarly `he_heading_degT`) is described as
> Heading of the low-numbered end of the runway in degrees true (not magnetic).

so I guess it could be directly usable.
The values calculated by `traffic` are

>	latitude	longitude	bearing	name
> 0	43.6374	1.35762	143.010038	14L
> 1	43.6156	1.38022	323.025631	32R
> 2	43.6441	1.34593	142.853913	14R
> 3	43.6190	1.37210	322.871970	32L

while those in OurAirports are

> "id","airport_ref","airport_ident","length_ft","width_ft","surface","lighted","closed","le_ident","le_latitude_deg","le_longitude_deg","le_elevation_ft","le_heading_degT","le_displaced_threshold_ft","he_ident","he_latitude_deg","he_longitude_deg","he_elevation_ft","he_heading_degT","he_displaced_threshold_ft"
> 235935,4070,"LFBO",9843,148,"ASP",1,0,"14L",43.6374,1.35762,490,143,,"32R",43.6156,1.38022,497,323,
> 235934,4070,"LFBO",11483,148,"ASP",1,0,"14R",43.6441,1.34593,488,143,,"32L",43.619,1.3721,497,323,

i.e. 143 for 14L/14R, 323 for 32R/32L

Well not sure reading from OA will improve things...
Any thoughts? Do you see the slight misalignment?

**Comment by espinielli** [comment]
Here is the latest AIP data (bearing as per OA data):
![Screen Shot 2021-11-21 at 15 24 54](https://user-images.githubusercontent.com/891692/142765787-eb636f20-7a40-4575-a57d-557113284b5b.png)

**Comment by xoolive** [comment]
Just had a look, indeed there is a difference but I guess this is a due to the nature of the projection. Look at the two examples:

![image](https://user-images.githubusercontent.com/1360812/145650546-95431a17-943f-41ff-b1ad-b6c62febcafb.png)
![image](https://user-images.githubusercontent.com/1360812/145650582-a21d6e0c-6d3a-404f-b048-e7ef67471892.png)

I assume that since Lambert93 is locally a better fit, North is up and angles match. With EuroPP, North is slightly shifted, but labels don't follow.

**Comment by xoolive** [comment]
So maybe, angles should be computed based on the projection with Matplotlib.
That wouldn't work so well with the geoencode() in Altair though.

**Comment by xoolive** [comment]
As stated above, the issue should persist in Altair.
With matplotlib, here goes with EuroPP:

![image](https://user-images.githubusercontent.com/1360812/145718645-2acf2989-95ee-47d0-a498-ace47504d0f9.png)
