### ISSUE TITLE
Conflict with Cartopy version

### ISSUE THREAD

**Issue by m-derra** [xoolive/traffic#179]
When trying to install the library either via conda in a new environment or via git clone and pip install .[dev] there seem to be conflicts with cartopy. I get the following error message:

> ERROR: Could not find a version that satisfies the requirement Cartopy<1.0.0,>=0.19.0 (from traffic[dev]) (from versions: 0.11.0, 0.12.0.4, 0.12.0.5, 0.13.0, 0.13.1, 0.14.0, 0.14.2, 0.15.1, 0.16.0, 0.17.0, 0.18.0b1, 0.18.0b2, 0.18.0rc1, 0.18.0, 0.19.0rc1, 0.19.0.post1, 0.20.0, 0.20.1, 0.20.2)
ERROR: No matching distribution found for Cartopy<1.0.0,>=0.19.0

**Comment by xoolive** [comment]
Can you give more details about your architecture (I suspect Linux here...)?
Also, can you try to install first cartopy and see which version you get?

**Comment by sauravrt** [comment]
I'm getting similar issues when installing on macOS arm64 architecture.
I tried both mamba and pip methods to install `traffic`, and still got conflicts with Cartopy version. 
Below is the tail of the message after failed pip install.
Let me know if more info is needed to help resolve this issue.

```
ERROR: Cannot install traffic==0.1, traffic==1.0, traffic==1.1, traffic==1.1.1, traffic==1.2, traffic==2.0, traffic==2.1, traffic==2.2, traffic==2.3, traffic==2.4, traffic==2.5, traffic==2.6, traffic==2.6.1, traffic==2.6.2, traffic==2.6.3, traffic==2.6.4, traffic==2.6.5 and traffic==2.6.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    traffic 2.6.6 depends on Cartopy<0.20.0 and >=0.19.0
    traffic 2.6.5 depends on Cartopy<0.20.0 and >=0.19.0
    traffic 2.6.4 depends on Cartopy<0.20.0 and >=0.19.0
    traffic 2.6.3 depends on pyarrow<5.0.0 and >=4.0.1
    traffic 2.6.2 depends on pyarrow<5.0.0 and >=4.0.1
    traffic 2.6.1 depends on Cartopy
    traffic 2.6 depends on Cartopy
    traffic 2.5 depends on Cartopy
    traffic 2.4 depends on Cartopy
    traffic 2.3 depends on Cartopy
    traffic 2.2 depends on Cartopy
    traffic 2.1 depends on Cartopy
    traffic 2.0 depends on Cartopy
    traffic 1.2 depends on Cartopy
    traffic 1.1.1 depends on Cartopy
    traffic 1.1 depends on Cartopy
    traffic 1.0 depends on Cartopy
    traffic 0.1 depends on Cartopy

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by xoolive** [comment]
Thank you for your feedback @sauravrt 

I am ready to do a release right away with fixed dependencies if need be but I need to identify what's wrong first.

Could you please install cartopy only in your environment (without traffic) and tell me which version you get?

**Comment by xoolive** [comment]
Just a small addition here: there is a known issue with Cartopy in Linux. Version 0.20 depends on a version of libproj which doesn't ship with Ubuntu. So it's impossible to have an up-to-date pip install without compiling libproj by yourself. You can have it with anaconda because they provide the libproj dependency for you. Otherwise you have to install version 0.19.something.post1. 

Anyway, with both cases, the current dependency should be correct
https://github.com/xoolive/traffic/blob/5784e96d538fa3e4acaa6ded1f373d1393067b83/pyproject.toml#L59

If you git clone the project, edit the dependency versions in pyproject.toml and manage to get a working install, please provide me that information :)

**Comment by xoolive** [comment]
@m-derra Thank you for the update. Indeed, it is better to come with fresh environments

**Comment by xoolive** [comment]
I'll close the issue now, @sauravrt please try to install again in a fresh environment and follow up on https://gitter.im/xoolive/traffic if needed
