### ISSUE TITLE
typing-extensions version dependency

### ISSUE THREAD

**Issue by eo93ed** [xoolive/traffic#180]
Hi,

Just installed traffic and an attempt to import lead to the follow version conflict,

Typing extension 4.0.1..... requirement.parse('typing-extentions<4.0.0>=3.10.0...

I tried reverting the typing extension to 4.0.0 but that failed due to other conflicts. Will a future version of traffic use 4.0.1 or will I need to find another solution??

Thanks

Eoin

**Comment by xoolive** [comment]
Hello Eoin,
I will check but I think it shouldn't be a problem to update traffic dependencies to up to date typing-extensions. In the meantime, you can:
- start from a fresh conda environment;
- git clone and edit the pyproject.toml to match the dependencies you need.

**Comment by eo93ed** [comment]
Hey,Sorry to bother you. Does this mean the dependency issue is sorted? Might try installation again later today!!I'm still very new to programming so Amy alternative options are usually over my head!!! I'm an air traffic controller trying to learn python so was very interested on traffic when I came across it!!EoinOn 14 Feb 2022 10:26, Xavier Olive ***@***.***> wrote:
Closed #180 via c385063.

**Comment by xoolive** [comment]
The dependency is updated on HEAD but it is not released yet. If you install after cloning the repository, you should be able to find your way.
