### ISSUE TITLE
Install stuck on "solving environment", followed install instructions. 

### ISSUE THREAD

**Issue by randomusername5** [xoolive/traffic#183]
I am attempting to install traffic with conda. I have followed the instructions on the installation page on the github. 
`conda create -n traffic -c conda-forge python=3.9 traffic`
`conda activate traffic`
However, the install gets stuck on solving environment. It will stay like this for some time, maybe over an hour. 

I have tried to install traffic with pip (in a fresh env), and was able to install it, but I got lots of version errors when importing. I ended up downgrading maybe a dozen or so packages, but was unable to successfully import traffic. 

I have not been able to find this same problem for traffic anywhere. 

Should I:
Just let the "solving environment" in the cmd line run for an extended period of time?
Some process as described in the below link?
https://github.com/conda/conda/issues/9367
Some other way? 

Thanks for your help!

**Comment by xoolive** [comment]
I have been aware that some people have this installation issue but have not been able to reproduce it myself in a fresh environment.

I need more details to try to assist you here.

- What is your operating system?
- Can you post the content of your condarc file? (I would like to check the `channel_priority` parameter in particular, but it's better if you can paste everything)
- Have you tried `mamba` which is faster at trying to solve the environment?

**Comment by randomusername5** [comment]
Thank you for very fast reply.

OS is Windows 10. 
I had tried to set priority strict when I attempted to install a couple weeks ago. I will take a look at the condarc file tomorrow. 
I am attempting to install mamba. It gives me:
`The environment is inconsistent, please check the package plan carefully`
Troubleshooting this is another issue, if I get mamba running, I will attempt to install traffic with mamba and report back. 
Again, thanks for your quick reply. I have looked at some use cases/examples for traffic and I am really excited to use it!

**Comment by xoolive** [comment]
You should remove the `strict` priority setting for Windows otherwise the system gets lost. I removed that from the installation instructions after I found it caused issues (not using Windows myself)

Try to install again (preferably with mamba, it is much faster) after reverting the setting:
```bash
conda config --set channel_priority disabled  # disabled for sure, default is flexible
```

**Comment by DRotherham** [comment]
I am also now experiencing severe issues with the installation of Traffic. After a DLL failure yesterday and the requirement to carry out a full installation for traffic I am similarly stuck in the loop for installing. I am using Windows 11.

**Comment by xoolive** [comment]
Hello @DRotherham I am sorry to hear that. Also I don't have a Windows 11 at hand to test. I updated the documentation yesterday, could you have a look and tell me if you are still stuck after that?

https://traffic-viz.github.io/troubleshooting/installation.html

**Comment by DRotherham** [comment]
Hello, @xoolive I have tested it with that but it doesn't appear to work. How does mamba work? Is it the same conda install instructions?

I can attach a screenshot if necessary to try and explain the issue in a better manner?

**Comment by xoolive** [comment]
Please come to https://gitter.im/xoolive/traffic for this kind of assistance

About mamba: https://github.com/mamba-org/mamba#installation
