### ISSUE TITLE
MIT license but contains a dependency to a GPLv3 library

### ISSUE THREAD

**Issue by plgregoire** [xoolive/traffic#184]
Hi,

I'm wondering why the library is licensed under the MIT license while containing a dependency on a library licensed under GPLv3

- pyModeS (https://github.com/junzis/pyModeS/blob/master/LICENSE)

By releasing under MIT license, the copyleft nature of GPLv3 seems to be lost.

Are you not required to release your library under the same license ?

**Comment by junzis** [comment]
Hi guys, I didn't pay much attention when selecting the license at the first place. Indeed, code that makes use of GPL also has to be released under GPL.

But I am going to offer a much simpler solution here. I will change pyModeS license to LGPL in the next release. Until then, I grant @xoolive the full right to use the pyModeS in  his traffic library. 

Let's make open-source license work for us, not against us. Cheers. 🖖🖖🖖

**Comment by xoolive** [comment]
Thank you

**Comment by plgregoire** [comment]
Great! Thank you.
