### ISSUE TITLE
Bug: Wrong distance calculation in cumulative_distance function

### ISSUE THREAD

**Issue by m-derra** [xoolive/traffic#197]
There is an error in the flight.py cumulative_distance function. Calculated distances appear to be wrong.

The error became obvious when calculating the ATS-efficiency (flown distance / great circle distance) for opensky ADS-B trajectories. In some cases the cumulative_distance was smaller than the great circle distance, which is not possible.

**Comment by xoolive** [comment]
Thank you for the bug report @m-derra 
would you have any sample trajectory I could look at to try to identify the bug?

**Comment by xoolive** [comment]
Thanks I will merge after the tests have passed.
If you had the example where the distance was smaller than the great circle distance, I would like to add that in the tests as well.
