### ISSUE TITLE
The live API often returns 18 fields instead of 17, which causes an exception.

### ISSUE THREAD

**Issue by simonrp84** [xoolive/traffic#208]
Hello,
For reasons I can't figure out, the Opensky live API sometimes returns 17 fields (as expected by `traffic`) but often returns 18 fields, which causes an exception as `_json_columns` isn't long enough. This doesn't seem to be documented and I'm not sure if this is intended by Opensky or not.

I wanted to mention it here for reference, and my fix is to change the lines after 235 in `data/adsb/opensky.py` to:
```
        try:
            c.raise_for_status()
            r = pd.DataFrame.from_records(
                c.json()["states"], columns=self._json_columns
            )
            
        except Exception as e:
            try:
                r = pd.DataFrame.from_records(
                c.json()["states"], columns=self._json_columns+['Bonus']
            )
            except Exception:
                logging.warning("Error in received data, retrying in 10 seconds")
                time.sleep(10)
                return self.api_states(own, bounds)
```

A better name for the extra field than `bonus` may be necessary ;)

**Comment by xoolive** [comment]
Thank you, actually this bug is annoying as it often fails the auto-generated documentation here:
https://traffic-viz.github.io/data_sources/opensky_rest.html#state-vectors

I will probably find something without cascaded `try/catch`. You will get the notification when it's done.

Do you have any idea of what is in the `bonus` column?

**Comment by simonrp84** [comment]
No, I don't know what's in the column - it seems to always be `0` from the data I've seen and I'm not sure what that represents.
