### ISSUE TITLE
Compression of OpenSky cache

### ISSUE THREAD

**Issue by aliaksei135** [xoolive/traffic#237]
I'm currently downloading a significant amount of data from OpenSky using the Impala Shell. Whilst I am waiting for this to complete, I found that the cached requests are currently stored in plain text. 

Is there scope to add functionality to compress the cached files to reduce disk space used?
Perhaps a kwarg like `compress` passed with `opensky.history` and an additional suffix on the filename to differentiate compressed and uncompressed files. This would likely use something like `zlib` to compress.

Happy to PR, just checking if this is desirable first.

**Comment by xoolive** [comment]
Thank you @aliaksei135 for the suggestion.

I don't know what's best, to be honest. In my mind, cache files are made to be discarded at some point anyway (there's a default expiration parameter in the config file)

But in a sense, why not compressing those 🤷, I wonder if it makes things slower though…

Let's start with a `compress` parameter (leave it by default to `False`, and we may silently switch to `True` later). Leave the filename as is, we can check for the header to see if it's a gzip as it starts with `1f 8b 08` [(wiki)](https://en.wikipedia.org/wiki/Gzip).

Thank you for the offer!
