### ISSUE TITLE
Notebook Crashes When running some cells

### ISSUE THREAD

**Issue by herozero777** [xoolive/traffic#260]
I was following the "Getting Started" page on traffic documentation website. I downloaded the quickstart.ipynb to experiment with the library as well. When I get to the cell with the code: 
```python
from cartes.crs import Lambert93
from traffic.data import airports

with plt.style.context("traffic"):

    fig, ax = plt.subplots(subplot_kw=dict(projection=Lambert93()))

    airports["LFPO"].plot(ax, footprint=False, runways=dict(linewidth=1))
    for flight in subset:
        flight.plot(ax, linewidth=2)

    ax.set_title("Landing trajectories at Paris–Orly airport")
```
The notebook crashes. Also the visualization on the Getting started page: https://traffic-viz.github.io/quickstart.html#declarative-trajectory-processing is missing well.

---
### To reproduce the issue 
Follow the quickstart.ipynb which can be downloaded from Getting Started page.

### Versions I'm using
Python==3.10.6
traffic==2.8.0

**Comment by xoolive** [comment]
Thank you for the report,

Would you mind trying what's here:
https://traffic-viz.github.io/troubleshooting/installation.html

Section “Python crashes when I try to reproduce plots in the documentation”

Please report here whether it solves your issue.

**Comment by xoolive** [comment]
Little addition wrt to the documentation, it seems I need to explicitly ask for the fig now, as follows:

```python
from cartes.crs import Lambert93
from traffic.data import airports

with plt.style.context("traffic"):

    fig, ax = plt.subplots(subplot_kw=dict(projection=Lambert93()))

    airports["LFPO"].plot(ax, footprint=False, runways=dict(linewidth=1))
    for flight in subset:
        flight.plot(ax, linewidth=2)

    ax.set_title("Landing trajectories at Paris–Orly airport")

fig
```

I will edit the documentation accordingly

**Comment by xoolive** [comment]
@herozero777 About item 2, I opened an issue: https://github.com/ipython/matplotlib-inline/issues/22
