### ISSUE TITLE
Problems with the installation

### ISSUE THREAD

**Issue by JoScheiderer** [xoolive/traffic#278]
I have a problem with the installation of the traffic environment. 
I receive the error: "Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source."

I work on a new MacBook Pro (M1) with MacOS Ventura (previous Monterey, same issues).
I already updated condo, de-installed and re-installed Anaconda.  No success.

Does anybody has an idea? 

Thanks 
joe

**Comment by xoolive** [comment]
@JoScheiderer I asked around to people with a M1 and they couldn't reproduce your issue... Did you try with a fresh anaconda environment?

**Comment by JoScheiderer** [comment]
@xoolive I had it running on the same machine in the past, but then wanted to reset it. I have also already completely deleted and uninstalled he environment and reinstalled Anaconda. Unfortunately, the installation always gets stuck at the same place (right at the beginning).

<img width="585" alt="image" src="https://user-images.githubusercontent.com/69255423/199250189-019e25bd-abc9-400f-845f-d606b475a9ae.png">

The image shows the terminal window. The "solving environment" is something like an endless loop. It keeps going until the terminal window is terminated (I tried it several hours).
I am quite new to this, so sorry for asking perhaps stupid questions... what is a "new anaconda environment" or how can I make one apart from delete everything? 

Thanks for your help.

**Comment by mdlugosz-agh** [comment]
I confirmed this error. I try to install traffic on "new and fresh" anaconda version (running as container from official anaconda image) and I have the same problem.

**Comment by JoScheiderer** [comment]
I think, I solved it (or my Computer did). After 2,5 h of "solving environment" it finally worked out and the condo finished the installation. It was my fourth attempt, where the computer run for more than 2 hours on this issue. Finally it worked...

**Comment by xoolive** [comment]
That is really not sustainable… mamba is a good alternative for that resolution process. Otherwise I’ll try to relax version numbers even more in next release. 

I have no idea what makes the resolution process difficult now 😞

**Comment by mdlugosz-agh** [comment]
After all night waiting still now instaled. Somebody could check it?
I try to install traffic in conda container [https://hub.docker.com/r/continuumio/anaconda3](https://hub.docker.com/r/continuumio/anaconda3)

**Comment by simonrp84** [comment]
Possibly related to this, I'm seeing errors with `mamba` after installing `traffic` on a (relatively) clean environment:
```
  File "C:\Users\Simon\miniconda3\lib\site-packages\OpenSSL\crypto.py", line 1577, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```
Looks like `traffic` is requiring `openssl` version 20.x, which is causing compatibility issues with other libraries that require more recent versions (I have openssl 0.23). Can this requirement be relaxed?

**Comment by xoolive** [comment]
Hi all, I just did a traffic release on conda-forge (it was done on pip earlier this week), and the install was really fast on a clean miniconda.
They seem to have improved things in conda as well, so be sure to update your conda!

@simonrp84 that dependency constraint is now relaxed
