### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'agg_latlon'

### ISSUE THREAD

**Issue by mdlugosz-agh** [xoolive/traffic#279]
Hi, 
I try to reuse heatmap example.
I download and save in pickle file data like before_covid19 and after_covid19.
Next I read this data from pickle file using:
`before_covid19 = pickle.load( open( "before_covid19.pkl", "rb") )
after_covid19 = pickle.load( open( "after_covid19.pkl", "rb") )`
and try to run second part of heatmap example where heatmap plot is created.
Unfortunately I have a error: AttributeError: 'DataFrame' object has no attribute 'agg_latlon'

I use docker version of traffic library and to reproduce error this short code can be user:
```
from traffic.data import opensky
import matplotlib.pyplot as plt

from matplotlib.offsetbox import AnchoredText
from mpl_toolkits.axes_grid1.inset_locator import inset_axes

from cartopy.crs import EuroPP, PlateCarree
from cartes.utils.features import countries, ocean
import pickle

before_covid19 = pickle.load( open( "before_covid19.pkl", "rb") )
before_covid19.query("altitude>1000").agg_latlon(
                # 10 points per integer lat/lon
                resolution=dict(latitude=10, longitude=10),
                # count the number of flights
                flight_id="nunique"
            )
```

---

Please follow these steps to make it more efficient to solve your issue:

- [x] Search for duplicate issues.
- [x] Use the latest version of traffic, ideally the HEAD of the github, and activate the `DEBUG` logging level.
- [x] Describe how to reproduce the bug and include the full code and data to reproduce it, ideally using a sample trajectory from the library. Sample trajectories are extensively used in the tests suite.
- [x] Limit the output of your exceptions to what is strictly necessary.

You may activate the `DEBUG` level with the following snippet:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by xoolive** [comment]
Just replace 

```python
before_covid19 = pickle.load( open( "before_covid19.pkl", "rb") )
```

with

```python
before_covid19 = Traffic.from_file("before_covid19.pkl")
```
