### ISSUE TITLE
AIRAC RuntimeError

### ISSUE THREAD

**Issue by babetoduarte** [xoolive/traffic#3]
Hello, 

I'm trying to make use of traffic to download data from OpenSky. I have already configured my credentials in the configuration file, but now I get an error regarding the AIRAC directory:

`RuntimeError: Edit file /Users/jad/Library/Application Support/traffic/traffic.conf with AIRAC directory` 

I really do not know how to proceed with this, as I am not very familiar with Air Traffic information systems. How should I proceed in order to be able to use traffic as an easy access point to OpenSky data?

I appreciate you help with this matter. 

Thanks, 

Jorge.

**Comment by xoolive** [comment]
Hello,

I am sorry you encounter this issue. In theory, you should be able to download from OpenSky without AIRAC data. I will investigate when I am back, but before that could you help by (please) copy-pasting here the smallest piece of code that creates this error?

Thank you

**Comment by babetoduarte** [comment]
Hello Xavier, 

I get this error while trying to run the example that is shown in the project's Readme:

`traffic opensky 2018-01-01T06:00 -s 2018-01-01T08:00 -b Andorra -o andorra.pkl`

Here's the dump:

`Traceback (most recent call last):
  File "/Users/jad/anaconda3/envs/python3/bin/traffic", line 11, in <module>
    sys.exit(main())
  File "/Users/jad/anaconda3/envs/python3/lib/python3.6/site-packages/traffic/console/__init__.py", line 62, in main
    return mod.main(args.args)
  File "/Users/jad/anaconda3/envs/python3/lib/python3.6/site-packages/traffic/console/opensky.py", line 76, in main
    opensky_data(**vars(args))
  File "/Users/jad/anaconda3/envs/python3/lib/python3.6/site-packages/traffic/console/opensky.py", line 15, in opensky_data
    kwargs["bounds"] = airac[bounds]
  File "/Users/jad/anaconda3/envs/python3/lib/python3.6/site-packages/traffic/data/airspaces/airac.py", line 301, in __getitem__
    return next(self.search(name, operator.eq), None)
  File "/Users/jad/anaconda3/envs/python3/lib/python3.6/site-packages/traffic/data/airspaces/airac.py", line 308, in search
    self.init_cache()
  File "/Users/jad/anaconda3/envs/python3/lib/python3.6/site-packages/traffic/data/airspaces/airac.py", line 79, in init_cache
    raise RuntimeError(msg)
RuntimeError: Edit file /Users/jad/Library/Application Support/traffic/traffic.conf with AIRAC directory`

Thank you very much for your help.

Happy Holidays!

**Comment by xoolive** [comment]
I see! That’s my mistake but it should be very easy to fix... 👍
It’s not a problem in the library but in the script. I can probably push the fix in about 48h.

**Comment by xoolive** [comment]
@babetoduarte you may try now (`git pull` then `python setup.py install`)

**Comment by babetoduarte** [comment]
@xoolive thank you very much for the quick fix. I was able to run the example code correctly once I updated my local copy of `traffic`. 

I have one last question, I am trying to obtain flight track data over the US, however I can't seem to figure out the proper _bound_ name I must use in order to gather OpenSky data over this region. Is there any documentation on this? Can I provide coordinates for a bounding box instead of a name?

Thank you very much for your help.

Happy New Year!

**Comment by xoolive** [comment]
@babetoduarte Yes you can try option `-b " -127,24,-65,50"` (order is west/south/east/north)


Note the classical bracket-space-hyphen trick if you want to pass a negative number that is not an argparse argument:

```
-b " -127,24,-65,50"
   ^^^
```

Also, I usually go to https://www.openstreetmap.org/, click "export" then get a way to get the coordinates of a bounding box (that's how I came with those numbers)

If it gets too complex with the command-line tool, it will probably be easier to use the [library](https://airtraffic.readthedocs.io/en/latest/opensky_usage.html#access-to-the-impala-shell) and look at the help of each function. (This specific function should be properly documented)
