### ISSUE TITLE
JOSS Review: access to NM AIRAC data not clear

### ISSUE THREAD

**Issue by espinielli** [xoolive/traffic#31]
The part of the QS that says

If you have access to AIRAC files (published by Eurocontrol), you may get information about more complex zones, here the Terminal Maneuvering Area (TMA) for Toulouse.
```python
from traffic.data import nm_airspaces
nm_airspaces['LFBOTMA']
```
fails for me...(and subsequent ones where `nm_airspaces` is used)
Does it need some additional data sources?
Probably a link to [Data Sources](https://traffic-viz.github.io/airac_usage.html) would help...

**Comment by xoolive** [comment]
Thank your for the extensive feedback and for pointing at such dark corners of the documentation!

How does it fail for you? Do you have a proper error message suggesting to edit the configuration file? Do you mean you would like to see the link to the documentation page in the exception or do you mean it would be better to add this link in the quickstart page? or both?

**Comment by espinielli** [comment]
I think it would be good to mention the link in the Quick Start documentation.

**Comment by espinielli** [comment]
If I run

```python
from traffic.data import nm_airspaces
nm_airspaces['LFBOTMA']
```

I get

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-11-76c3defdfd9c> in <module>
>       1 from traffic.data import nm_airspaces
> ----> 2 nm_airspaces['LFBOTMA']
> 
> ~/kaos/traffic/traffic/data/airspaces/eurocontrol_nm.py in __getitem__(self, name)
>     120 
>     121         if not self.initialized:
> --> 122             self.init_cache()
>     123 
>     124         list_names = self.airspaces.get(name, None)
> 
> ~/kaos/traffic/traffic/data/airspaces/eurocontrol_nm.py in init_cache(self)
>      35 
>      36         if self.nm_path is None:
> ---> 37             raise RuntimeError(msg)
>      38 
>      39         are_file = next(self.nm_path.glob("Sectors_*.are"), None)
> 
> RuntimeError: Edit file /Users/espin/Library/Application Support/traffic/traffic.conf with NM directory
> 
> 

which clearly says to properly edit your config directory, but at this stage of the QS you do not even have any idea about the airspace data, hence a link to the relevant section in the docs would be beneficial...

**Comment by xoolive** [comment]
Added a warning block at this stage of the documentation with the relevant link. Thanks for pointing at it!
