### ISSUE TITLE
Issue with getting tracks from OpenSky REST API 

### ISSUE THREAD

**Issue by dazzag24** [xoolive/traffic#34]
Hi,

I've been following the examples here:
https://traffic-viz.github.io/opensky_usage.html

```
import random
sample_callsigns = random.sample(sv.callsigns, 6)
sample_callsigns
['RCH319', 'KZR921', 'SKW5996', 'N21714', 'JSA538', 'DAL2225']
```

```
flight = sv[sample_callsigns[5]]
flight
```

returns the following error:

```
HTTPError: 404 Client Error:  for url: https://opensky-network.org/api/tracks/?icao24=acbe7a
```

Any hints on how to overcome this?

Many thanks

**Comment by xoolive** [comment]
Thank you @dazzag24 for your feedback.

Unfortunately, this issue occurs on the server side. It has been off for a while now. You may want to pick at @affitz about that. I think the `tracks/` target is the only one that is dysfunctional at the moment.

I will leave the issue open until it is closed on the server side.

**Comment by dazzag24** [comment]
Thanks for the reply.
