### ISSUE TITLE
ADS-B Report low aircraft my receiver detects 

### ISSUE THREAD

**Issue by Mike-D-424** [xoolive/traffic#426]
I wish to find a magic way for my existing ADS-B feed to create and (preferably e-mail me) a daily report including aircraft ID, speed, heading, date, time, altitude, etc. of any aircraft lower than 1000 ft that my device receives.  

The reason I want this is I am tired of helicopters making my house shake since I live under their approach to a local airport.  

I am not at all a coding or pi expert, therefore the simpler and easier-to-implement solution is preferred.  

Thank you,  Michael

**Comment by xoolive** [comment]
There's no magic way to do the job.
It's possible to code it with this library (and others), but that's another project.
