### ISSUE TITLE
Expired security certificate for http://ourairports.com/data/airports.csv

### ISSUE THREAD

**Issue by iavrekh** [xoolive/traffic#464]
Cannot run code with freshly installed traffic library v 2.10.2.
Apparently, security certificate for website http://ourairports.com/data/airports.csv has expired a few days ago.
Reproducible by going directly to this website.

**Comment by iavrekh** [comment]
Sorry, I meant "https"!

**Comment by xoolive** [comment]
The certificate just expired few days ago. Let's give them some time to update it. Can't do anything from the library side

**Comment by iavrekh** [comment]
Understood, thanks! Good to know they are aware of the issue.

**Comment by iavrekh** [comment]
Bypassed for now by copying files 
"runways_ourairports.pkl"  and "airports_ourairports.parquet"
from the recent installation into cache directory ~/.cache/traffic/

**Comment by xoolive** [comment]
I think the certificate is fixed now, no?

**Comment by iavrekh** [comment]
Yes, it's fixed! Sorry for not checking before posting my comment.
