### ISSUE TITLE
Issues, apparently,  related to "PyArrow-backed" DataFrame in the fresh install of the Traffic library (v 2.10.2)

### ISSUE THREAD

**Issue by iavrekh** [xoolive/traffic#465]
Fresh install of the Traffic library v. 2.10.2 in a separate conda environment (from conda-forge), as described in documentation.
Contains: Python 3.12.7, numpy 1.26.4, pandas 2.2.3, trino-python-client 0.330.0,
pyarrow, pyarrow-core 17.0.0
Retrieving data from OpenSky repository using Trino client.

# Issue 1

In the DataFrame underlying Flight object, "onground" indicator has "bool[pyarrow]" type.
It causes the following statement in "format_history" method in opensky.py:
	if "onground" in df.columns and df.onground.dtype != bool:
        df.onground = df.onground == "true"
to set all "onground" values to False.

# Issue 2

The "timestamp" in the DataFrame underlying Flight object, has "timestamp[ns, tz=UTC][pyarrow]" type, 
"Flight.at(time)" method implementation in flight.py forces conversion of the "time" 
parameter passed as "pd.Timestamp" into "datetime.datetime", but then fails to find this value 
in the respective DataFrame index, returning "None" as the result.
Everything works fine if we bypass 
index = to_datetime(time)
conversion.
```
Both cases probably, point to the fact that we are dealing with "Arrow-backed DataFrame", which was not the case with an earlier version supporting Trino, however, I cannot fully account for all the reasons it could've happened, not I'm fully in command of PyArrow functionality.

**Comment by xoolive** [comment]
Indeed the pyarrow backend improves performance by a lot... so now that it's switched, I have to fix the bugs when they appear.
Thanks for raising these issues, will check and fix asap

**Comment by xoolive** [comment]
In the future, please just open one ticket per issue :pray:

**Comment by iavrekh** [comment]
You are absolutely right - I was carried away by the seemingly common "PyArrow" theme. :)

**Comment by xoolive** [comment]
Let me close the issue, let's confirm in #468 that everything works
When confirmed, I will merge into master
