### ISSUE TITLE
Issue with "Flight. split" method, likely related to "PyArrow-backed" DataFrame

### ISSUE THREAD

**Issue by iavrekh** [xoolive/traffic#466]
Fresh install of the Traffic library v. 2.10.2 in a separate conda environment (from conda-forge).
Contains:
Python 3.12.7, numpy 1.26.4, pandas 2.2.3, trino-python-client 0.330.0
pyarrow, pyarrow-core 17.0.0

"_split" method in flight.py doesn't work correctly

diff = data.timestamp.diff().values
…
max_ = np.nanmax(diff)

The last statement returns max_= NaT, most likely, due to timestamp values having "timestamp[ns, tz=UTC][pyarrow]" type
and, as the result, "diff" values being of "duration[ns][pyarrow]" type.

**Comment by iavrekh** [comment]
Code to reproduce the issue attached:
SplitTestA.py - using "pickled" Traffic object (file TwoFlightsFromOpenSky.pkl) containing two flights "excerpted" 
from the set of flights in Terminal Maneuvering Area (TMA) around KPWM (Portland International Jetport, Portland, Maine,USA) 
on 2024-07-01, downloaded from OpenSky repository. Both flights are overflights of the area by the same aircraft - they have the same icao24 value, but different callsigns. The program manipulates the second flight by making both callsigns the same. 
The Traffic.iterate method fails to separate them after that despite the gap larger than 10 minutes.

SplitTestB.py - "contrasting" example using Belevingsvlucht dataset. Flight.split method works fine in this case.
If you put debug printing for "max_" in "_split" method you'll see that the value is "NaT" in the first case, but 
meaningful in the second one.

[Split.zip](https://github.com/user-attachments/files/17547883/Split.zip)

**Comment by xoolive** [comment]
Let me start a branch to fix all these pyarrow related issues, with a related PR
Let's check it there

**Comment by iavrekh** [comment]
Thanks! I hope these small pieces of code could be useful.
Providing my real "production" code would've been quite impractical due to the size and complexity, but the data in the provided small example is "real".

**Comment by xoolive** [comment]
Let me close the issue, let's confirm in #468 that everything works
When confirmed, I will merge into master
