### ISSUE TITLE
Opensky history is returning wrong times

### ISSUE THREAD

**Issue by simonrp84** [xoolive/traffic#55]
Hi Xavier,
I have this code:
```
from traffic.data import opensky, airports
from datetime import timedelta, datetime
lat_ave,lon_ave = airports['VABB'].latlon
bounds = [lon_ave - 0.45, lat_ave - 0.45,
          lon_ave + 0.45, lat_ave + 0.45]
st_time = datetime(2019,8,19,11,8,0)
flights = opensky.history(start=st_time,
                          stop=st_time+timedelta(minutes=1),
                          bounds=bounds,
                          other_params=" and time-lastcontact<=15 ")
```
Which I think should give me flights at `11:08 UTC` on 19th Aug 2019. *But* it actually gives me flights for `10:08 UTC`.
I guess this is some kind of timezone thing (although I'm on UTC). Any ideas?

**Comment by xoolive** [comment]
Hello Simon,

The thing is that the datetime you provide is tz-naive. You may add some [tzinfo](https://docs.python.org/3/library/datetime.html#datetime.datetime) argument to have a tz-aware timestamp.

But then, from where your location, there should be no problem, right?

Could you try the following and confirm the issue?

```python
flights = opensky.history(
    start="2019-08-19 11:08",
    stop=timedelta(minutes=1),
    bounds=bounds,
    other_params=" and time-lastcontact<=15 "
)
```

Please don't close the issue even if this solves the problem. tz-naive timestamps are valid for retro-compatibility reasons but I think I should add a warning when people pass these...

**Comment by simonrp84** [comment]
Thanks for the quick reply. Your suggestion does solve the problem, yes!

**Comment by xoolive** [comment]
You will get a proper warning with the hereabove commit.
