### ISSUE TITLE
Impala error when querying with airports parameters

### ISSUE THREAD

**Issue by liquidsun** [xoolive/traffic#56]
Hi!
First of all, thanks for the library, it is really awesome!

I were getting errors when tried to make a query to Opensky historical database
with airport, arrival_airport or departure_airport parameters.
The error is related to Impala shell query:
```python
opensky.history(
    "2019-01-19", "2019-01-20",
    airport="LOWS")
```
```
ImpalaError: time	icao24	lat	lon	velocity	heading	vertrate	callsign	onground	alert	spi	squawk	baroaltitude	geoaltitude	lastposupdate	lastcontact	hour
select time, icao24, lat, lon, velocity, heading, vertrate, c
callsign, onground, alert, spi, squawk, baroaltitude, geoaltitude, lastposupdate,
, lastcontact, hour from state_vectors_data4 as sv join (select icao24, firstseen
n, estdepartureairport, lastseen, estarrivalairport, callsign, day from flights_d
data4 where estarrivalairport ='LOWS' and (1553904000 <= day and day <= 155407680
00)) as est on sv.icao24 = est.icao24 and sv.callsign = est.callsign and est.firs
stseen <= sv.time and sv.time <= est.lastseen where hour>=1553904000.0 and hour<1
1553907600.0 and time>=1553904000.0 and time<1553990400.0 ;

ERROR: AnalysisException: Column/field reference is ambiguous: 'icao24'
```
So I've assigned labels for 'icao24' and 'callsign' in flights_data4 table in opensky_impala.py in parts of the query related to airports (rows 654 - 685)  and put same labels in join part (rows 625 - 629).
It works now for me. 
All the best.

**Comment by xoolive** [comment]
Thank you for for the support @liquidsun 

Oh I know this error, it is not a fun one because it happens only "sometimes". I thought it was sorted but I was able to reproduce the issue on my side.

Are you comfortable with making a pull request?
If not, I will try to interpret your fix (do you mean writing `est.icao24` instead of `icao24`?) and merge it into the code in the coming week...

**Comment by liquidsun** [comment]
I am quite new to active usage of GitHub, haven't figure out how everything works here yet.
I put ```icao24 as est_icao24``` and ```callsign as est_callsign``` in airport related parts of query and then ```"on sv.icao24 = est.est_icao24 and"
   "sv.callsign = est.est_callsign"``` in join part. Not sure though if it might affect somehow other parts of library, but for me it worked out well.

**Comment by xoolive** [comment]
OK that's crystal clear, I can do that.
Thank you for the feedback!

PS: Didn't suspect Salzburg had coverage on OpenSky 😉
