### ISSUE TITLE
Issue importing SO6 (DDR files from ECTL)

### ISSUE THREAD

**Issue by yves-austrocontrol** [xoolive/traffic#60]
I get the following error message when importing SO6.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-22-aba3a48a097b> in <module>
----> 1 from traffic.data.so6 import so6
      2 #so6 = SO6.from_file('20190708_m1.so6')
      3 #so6.to_pickle('./data/sample.pkl')

ModuleNotFoundError: No module named 'traffic.data.so6'

---------------------------------------------------------------------------
Have you also had this issue ?
Best,
Yves

**Comment by xoolive** [comment]
Hello Yves,

Sorry for that, it's my fault. I moved things a bit abruptly as I started implementing more things for interactions with Eurocontrol files and services.

You should now be able to run:

```python
from traffic.data import SO6

so6 = SO6.from_file("20190708_m1.so6')
```

Please confirm whether this work before I can close the issue.

**Comment by xoolive** [comment]
I had updated [this page](https://traffic-viz.github.io/so6_usage.html) of the documentation, but did you find this "old style" import in your scripts or in another part of the documentation?

**Comment by yves-austrocontrol** [comment]
Hi Xavier,
It was in my scripts ! 
It works with the current documentation syntax. Thanks !
Best,
Yves

**Comment by xoolive** [comment]
Great! Glad it’s still helpful :)
