### ISSUE TITLE
Callsign error in rawdata method in opensky_impala.py

### ISSUE THREAD

**Issue by Wirden** [xoolive/traffic#75]
Line 1010 of `opensky_impala.py` :

`callsigns += "and callsign='{:<8s}' ".format(callsign)`

triggers `UnboundLocalError: local variable 'callsigns' referenced before assignment`

upon call like :  

`df = opensky.rawdata(start=start_date, stop=end_date, callsign=callsign, cached=False)`

**HOW TO FIX** : change Line 1010 of `opensky_impala.py` to : 

`callsigns = "and callsign='{:<8s}' ".format(callsign)`

**Comment by xoolive** [comment]
thanks
