### ISSUE TITLE
'Flight' object has no attribute 'latitude' (similar with 'longitude' and 'altitude')

### ISSUE THREAD

**Issue by scorrado10** [xoolive/traffic#78]
Hi,

I am trying to go through the quickstart guide. I have the following code:

`from traffic.data.samples import belevingsvlucht
belevingsvlucht`

I then receive the following error, which I assumed was related to the plotting:
```
Traceback (most recent call last):

  File "C:\Users\scorrado3\Anaconda3\lib\site-packages\IPython\core\formatters.py", line 345, in __call__
    return method()

  File "C:\Users\scorrado3\Anaconda3\lib\site-packages\traffic-2.3.1-py3.7.egg\traffic\core\flight.py", line 227, in _repr_html_
    return title + no_wrap_div.format(self._repr_svg_())

  File "C:\Users\scorrado3\Anaconda3\lib\site-packages\traffic-2.3.1-py3.7.egg\traffic\core\flight.py", line 248, in _repr_svg_
    cast(Flight, coords_only.simplify(25)),

  File "C:\Users\scorrado3\Anaconda3\lib\site-packages\traffic-2.3.1-py3.7.egg\traffic\core\flight.py", line 1531, in simplify
    **kwargs,

  File "C:\Users\scorrado3\Anaconda3\lib\site-packages\traffic-2.3.1-py3.7.egg\traffic\algorithms\douglas_peucker.py", line 121, in douglas_peucker
    pyproj.Proj(init="EPSG:4326"), projection, lon.values, lat.values

  File "C:\Users\scorrado3\Anaconda3\lib\site-packages\pyproj\__init__.py", line 362, in __new__
    return _proj.Proj.__new__(self, projstring)

  File "_proj.pyx", line 129, in _proj.Proj.__cinit__

RuntimeError: b'no arguments in initialization list'

Traceback (most recent call last):

  File "C:\Users\scorrado3\Anaconda3\lib\site-packages\IPython\core\formatters.py", line 345, in __call__
    return method()

  File "C:\Users\scorrado3\Anaconda3\lib\site-packages\traffic-2.3.1-py3.7.egg\traffic\core\flight.py", line 248, in _repr_svg_
    cast(Flight, coords_only.simplify(25)),

  File "C:\Users\scorrado3\Anaconda3\lib\site-packages\traffic-2.3.1-py3.7.egg\traffic\core\flight.py", line 1531, in simplify
    **kwargs,

  File "C:\Users\scorrado3\Anaconda3\lib\site-packages\traffic-2.3.1-py3.7.egg\traffic\algorithms\douglas_peucker.py", line 121, in douglas_peucker
    pyproj.Proj(init="EPSG:4326"), projection, lon.values, lat.values

  File "C:\Users\scorrado3\Anaconda3\lib\site-packages\pyproj\__init__.py", line 362, in __new__
    return _proj.Proj.__new__(self, projstring)

  File "_proj.pyx", line 129, in _proj.Proj.__cinit__

RuntimeError: b'no arguments in initialization list'
```

My next step was to try to plot myself, using the latitude and longitude, as I had seen the Flight object must contain latitude and longitude. To be sure of this I typed:
`belevingsvlucht.latitude`
I got the following error:
```
Traceback (most recent call last):

  File "<ipython-input-5-e5e5d8f1fc78>", line 1, in <module>
    belevingsvlucht.latitude

AttributeError: 'Flight' object has no attribute 'latitude'
```
I then tried similarly with longitude and altitude.

I then typed:
`dir(traffic.core.Flight)`

I received the following:
```
['__add__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__or__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_get_unique',
 '_info_html',
 '_repr_html_',
 '_repr_svg_',
 'abs',
 'after',
 'agg_time',
 'airborne',
 'aircraft',
 'area',
 'assign',
 'assign_id',
 'at',
 'at_ratio',
 'bearing',
 'before',
 'between',
 'bounds',
 'callsign',
 'centroid',
 'clip',
 'closest_point',
 'comet',
 'compute_wind',
 'compute_xy',
 'coords',
 'coords4d',
 'cumulative_distance',
 'data',
 'destination',
 'diff',
 'distance',
 'drop',
 'drop_duplicates',
 'duration',
 'encode',
 'extent',
 'feature_gt',
 'feature_lt',
 'fillna',
 'filter',
 'filter_if',
 'first',
 'flight_id',
 'from_file',
 'geoencode',
 'geojson',
 'groupby',
 'guess_landing_airport',
 'guess_takeoff_airport',
 'handle_last_position',
 'icao24',
 'inside_bbox',
 'intersects',
 'last',
 'leaflet',
 'linestring',
 'longer_than',
 'max',
 'max_split',
 'mean',
 'merge',
 'min',
 'number',
 'origin',
 'pipe',
 'plot',
 'plot_time',
 'plot_wind',
 'point',
 'project_shape',
 'query',
 'query_ehs',
 'query_opensky',
 'registration',
 'rename',
 'resample',
 'reset_index',
 'shape',
 'shorter_than',
 'simplify',
 'sort_values',
 'split',
 'squawk',
 'start',
 'stop',
 'timestamp',
 'title',
 'to_csv',
 'to_excel',
 'to_hdf',
 'to_json',
 'to_parquet',
 'to_pickle',
 'typecode',
 'unwrap',
 'xy_time']
```
It is evident that altitude, latitude, and longitude are not on this list.

So, I am wondering if the tutorial is out of date, and why the Flight object no longer has latitude and longitude as attributes?

Thank you!

**Comment by xoolive** [comment]
You can get access to all features of a flight through the underlying dataframe. 

Try `belevingsvlucht.data.latitude` for the latitude information. (Same with altitude, vertical_rate, etc.)

**Comment by xoolive** [comment]
Then I’m not sure about the visualisation issue but it may be fixed on master. I don’t have the issue on my side. Can you confirm the issue after upgrading?

**Comment by scorrado10** [comment]
Ah okay, yes, the underlying DataFrame is, in fact, there, sorry about that!

In terms of the visualization, I have upgraded and the issue persists. Additionally, I have installed the development version and also cloned the repo, unfortunately to still get the same error.

**Comment by scorrado10** [comment]
I have gotten the plot to show by updating my pyprog package; however, I get these warnings:
`site-packages\pyproj\crs\crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
C:\Users\scorrado3\Anaconda3\lib\site-packages\pyproj\crs\crs.py:294: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  projstring = _prepare_from_string(" ".join((projstring, projkwargs)))
C:\Users\scorrado3\Anaconda3\lib\site-packages\pyproj\crs\crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
C:\Users\scorrado3\Anaconda3\lib\site-packages\pyproj\crs\crs.py:294: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  projstring = _prepare_from_string(" ".join((projstring, projkwargs)))
C:\Users\scorrado3\Anaconda3\lib\site-packages\pyproj\crs\crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
C:\Users\scorrado3\Anaconda3\lib\site-packages\pyproj\crs\crs.py:294: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  projstring = _prepare_from_string(" ".join((projstring, projkwargs)))
C:\Users\scorrado3\Anaconda3\lib\site-packages\pyproj\crs\crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
C:\Users\scorrado3\Anaconda3\lib\site-packages\pyproj\crs\crs.py:294: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  projstring = _prepare_from_string(" ".join((projstring, projkwargs)))`

Would you be able to tell me what version of pyproj you are using so I can install that version?

Also, I get this warning when I first run the `from traffic.data.samples import belevingsvlucht` piece of code, so I think there may have been several deprecations since the package was first developed:

` DeprecationWarning: Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future release.
  self, resource_name
C:\Users\scorrado3\Anaconda3\lib\site-packages\ipyleaflet\leaflet.py:338: DeprecationWarning: metadata {'dtype': None} was set from the constructor. With traitlets 4.1, metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
  data = Dataset().tag(dtype=None, sync=True, to_json=ds_x_to_json)
C:\Users\scorrado3\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:454: DeprecationWarning: `input_splitter` is deprecated since IPython 7.0, prefer `input_transformer_manager`.
  status, indent_spaces = self.shell.input_splitter.check_complete(code)`

**Comment by xoolive** [comment]
Currently I have on one my computers

```
pyproj==2.4.2.post1
Shapely==1.6.4.post2
```

Do you think you could find your failing pyproj version so I can hardcode the dependency in the setup.py file?

I have some of these DeprecationWarning as well, but honestly I am not sure I have that much. How about setting up a fresh conda or virtualenv environment to be sure to have the latest versions?

It looks like I there is no issue anymore so I will close this one. Don't hesitate to open a new issue if something else arises.

**Comment by scorrado10** [comment]
Thank you for your help!

I actually did uninstall and reinstall my anaconda today completely because originally I thought something was wrong with it, so everything I have now is pretty fresh.

If I remember correctly, the version of pyproj that was failing was 1.9.6, and I have it at 2.6.0 now where it is only giving me the deprecation warnings.
