### ISSUE TITLE
aircraft.query produces a TypeError

### ISSUE THREAD

**Issue by simonrp84** [xoolive/traffic#79]
Hi,
I'm trying to use `aircraft.query` as in the example:
```
from traffic.data import aircraft
aircraft.query(registration="^F-ZB", model="EC45").head()
```

But I get this error:
```
Traceback (most recent call last):
  ...
TypeError: 'Series' objects are mutable, thus they cannot be hashed
```

Any ideas what the problem could be there?

(edit) This happens with both the release version and the latest version from github.

**Comment by xoolive** [comment]
That's weird... I can't reproduce it on my side. 😟 

A similar line passes the tests on travis on 3 versions of Python:
https://github.com/xoolive/traffic/blob/c3cafc4298536538a6c8e73c6ec1bde1c8050021/tests/test_aircraft.py#L37

Maybe your db is corrupted, then you can try downloading a new version?
```python
aircraft.download_opensky()
```

**Comment by simonrp84** [comment]
It seems that this may be a `pandas` issue: https://github.com/pandas-dev/pandas/issues/26549

I can fix the issue by changing, for example:
`return self._fmt(self.data.query("registration.str.contains(@name)"))`
to
`return self._fmt(self.data.query("registration.str.contains(@name)", engine='python'))`
Unfortunately this is quite slow, but I guess we need to wait for a pandas update. Would be interesting to know why it works on your machine but not mine, though!

**Comment by xoolive** [comment]
I am with `pandas==1.0.1` (MacOS and Linux though I am not sure it makes a difference)

**Comment by simonrp84** [comment]
I've tested this on two linux machines, both running `pandas==1.0.3` and have the problem on both. One is a totally clean miniconda install, only required packages added.

Will check later what version of `pandas` my windows machine (which doesn't have the problem) is using.

**Comment by xoolive** [comment]
Do you have the same error without the `^` before `^F-ZB` ?

**Comment by simonrp84** [comment]
That gives the same error. I originally found this error as I was querying for specific icao24 codes, but it also occurs with registrations (not tried with any other variables).

**Comment by xoolive** [comment]
I switched to pandas 1.0.3 and I still can't reproduce the issue...

**Comment by simonrp84** [comment]
Sorry for the lack of updates, it slipped my mind.
I just tried this again on the latest `traffic` from github and pandas `1.0.4`...it still produces the error message given above on one of my machines. The other machine is (as before) successful. Very weird, they're running the same version of all the libraries I think have relevance.

**Comment by xoolive** [comment]
OK, well let's leave the issue open until:
- either, I can reproduce the issue;
- or, somebody can't stand it anymore and fix it first 👍 

Not tempted?

**Comment by simonrp84** [comment]
I thought I'd already responded to this one too, but it seems not.
With a new install of anaconda I can't reproduce the issue any more so probably it was some local problem.

I'll close this, and will reopen if it happens again :)

**Comment by RunningCarla** [comment]
I had the same error message with pandas when I worked with the traffic library. However, I was able to fix the issue by resetting the engine to default, as described here: /pandas-dev/pandas/issues/26549#issuecomment-496641475
```
import pandas as pd

def evaluate(self,expr,engine='python',**kw):
   return self._eval(expr,engine=engine,**kw)
   pd.DataFrame._eval = pd.DataFrame.eval
   pd.DataFrame.eval = evaluate
``` 
no issue on the traffic library side!
