### ISSUE TITLE
aligned_on_ils produces GeodError

### ISSUE THREAD

**Issue by ClaudiusBZ** [xoolive/traffic#81]
While trying out the newly implemented functions, I noticed that the method `aligned_on_ils` (in my case) always ends with an error for self downloaded trajectories. I use the latest version from Github.
If you use the example trajectory from the documentation, however, it runs fine. I used exactly the same syntax which is proposed by the documentation:

```
aligned = next(flight.aligned_on_ils('LOWW'))
print(f"ILS {aligned.max('ILS')} until {aligned.stop:%H:%M}")
```

The following error message is triggered:

```
Traceback (most recent call last):
  File "..../src/Test.py", line 11, in <module>
    aligned = next(flight.aligned_on_ils('LOWW'))
  File "....\anaconda3\envs\venv-traffic\lib\site-packages\traffic\algorithms\navigation.py", line 246, in aligned_on_ils
    self.bearing(threshold,)
  File "....\anaconda3\envs\venv-traffic\lib\site-packages\traffic\core\flight.py", line 1334, in bearing
    other.longitude * np.ones(size),
  File "....\anaconda3\envs\venv-traffic\lib\site-packages\traffic\core\geodesy.py", line 16, in bearing
    angle1, angle2, dist1 = geod.inv(lon1, lat1, lon2, lat2, *args, **kwargs)
  File "....\anaconda3\envs\venv-traffic\lib\site-packages\pyproj\geod.py", line 261, in inv
    self._inv(inx, iny, inz, ind, radians=radians)
  File "pyproj\_geod.pyx", line 117, in pyproj._geod.Geod._inv
pyproj.exceptions.GeodError: Array lengths are not the same.
```

Any ideas what kind of problem is there. Could it be related to the newly integrated version of pyproj?

**Comment by xoolive** [comment]
Hello Claudius,

I don't think it is about pyproj but I can try to debug it if you send the flight data. You can attach a pickle to the ticket or copy-paste the query to get the data.

I never had this issue. Nevertheless, it may be reasonable to ensure the flight is resampled before:
```python
flight.resample('1s').aligned_on_ils(...)
```

**Comment by ClaudiusBZ** [comment]
Hello Xavier, 

thank you for the fast response. Indeed resampling the flights was the solution so far. Maybe some timestamps were incomplete or missing. Now every example works like a charm :)

**Comment by xoolive** [comment]
By the way, you may want to try iterating on `.aligned_on_ils()` and get several attempts at landing at your airport... (not sure it's properly documented yet)

**Comment by ClaudiusBZ** [comment]
Thanks for the advice. I would like to add the runway to a traffic structure, so I will definitely try it. At the moment I have some difficulties with the `assign` method, because it does not add a new column to the dataframe during an iteration.

```
for flight in data:
    flight = flight.resample('1s')
    aligned = next(flight.aligned_on_ils('LOWW'))
    arrival_rwy = aligned.max('ILS')
    flight.assign(arr_rwy = arrival_rwy)
```

I describe it for documentation purposes, maybe the solution helps others as well.

**Comment by xoolive** [comment]
Ok, you may want to do
```
flight = flight.assign(...)
```

But on the other hand, I am not sure it is relevant to enrich it that way in the full flight because:
- a go-around does not necessarily lead to a second attempt on the same runway (or on the same airport!);
- careful, aligned on an ILS does not necessarily mean you will land on this runway. I have few trajectories at hand with circle to land maneuvers in LFPO (ILS 06 circle to land 07) or LSZH (ILS 14 circle to land 16) or more with runway changes (common in LFBO for instance: aligned on 32L then changing to 32R)

**Comment by ClaudiusBZ** [comment]
Thanks a lot, it worked. Your comments are of course correct, but in my application there are no parallel runways (for swing maneuvers) or applied circling procedures.
Maybe a crosscheck including `aligned_on_runway`, `track`, `onground` or/and `(geo)altitude` channel could be used for verification.
Are there plans to reimplement the runway estimation?

**Comment by xoolive** [comment]
I am open to any contribution :)

I don't plan to change things for the ILS, but may change small things if it helps in more corner cases.

What/How would you like to change the runway estimation? This one is a bit drafty, but not so bad in terms of accuracy when you have a good coverage on the runway, but there are of course several issues, including the fact it's hard to come back with a runway identifier... If you have a good/better one, let's include it!

**Comment by ClaudiusBZ** [comment]
Unfortunately, I have not yet implemented a new method. The points mentioned were rather thought games. Regarding the reimplementation I had reference to #53 .

If I should implement something similar in the course of my work, I will e happy to send it to you.

**Comment by xoolive** [comment]
The implementation mentioned in #53 was not great. Now there is this clarification between ILS and runway occupancy.

**Comment by TheYsconator** [comment]
```aligned_on_ils``` does not appear to be working for me. I don't know if this is related to this issue, or that I should open a new one.

In any case, I get the following error when using a snippet from the documentation.

![image](https://i.imgur.com/jgroqZG.png)

@xoolive can you let me know if this is expected behaviour?

**Comment by xoolive** [comment]
Please try to install traffic from github, the pip version is now seriously outdated. I will try to publish a new version before summer.

```
pip install git+https://github.com/xoolive/traffic
# or after git clone
pip install .
```

**Comment by TheYsconator** [comment]
Wow you're fast!

The method is indeed found when using the version from github, which resolves my issue. Thank you!
