### ISSUE TITLE
 COVID-19 on worldwide aviation -  flight lists with associated origin and destination airport  with OpenSky

### ISSUE THREAD

**Issue by victormartinezjurado** [xoolive/traffic#84]
Hello Xavier, 

Do you think it would be possible to know more in detail about how are you collecting and preparing the data available [here](https://opensky-network.org/datasets/covid-19/)?  As you described [here](https://opensky-network.org/datasets/covid-19/) data is obtained from impala Shell and monthly consolidated. I would be interested to programmatically obtain the data weekly or even daily.

**Comment by xoolive** [comment]
Hello @victormartinezjurado 

Thank you for your interest in this project.

Currently, the first step for producing the dataset is to dump the `flights_data4` table in the OpenSky database almost as is (i.e. the `opensky.flightlist` method). To be honest, the resulting information is enough for the plots in the documentation webpage.

However, the dataset contains more metadata information, including some from the OpenSky aircraft database (with few custom corrections that still need to be shared) and a flight number database which is not production-ready yet, and maintained by a fellow volunteer for OpenSky. At the moment, this flight number database (which associates a callsign to a commercial number) is unfortunately not publicly available.

For our next release, we plan to include more information per flight but I am still working on it. I will release a script which builds a first basic version of the (new version of the) dataset as soon as possible. But the final metadata enrichment will have to stay private for a longer while I am afraid.

**Comment by xoolive** [comment]
@victormartinezjurado I did not forget about you but had issue when trying to be smarter with the newer version of the dataset. I am kept pretty busy by external events but will keep you updated when the script is ready!

**Comment by xoolive** [comment]
@victormartinezjurado The script which downloads a non-curated shot of the (future version of the) dataset is `scripts/covid19_dataset.py`. It still works even if you don't have the flight database (option `-f`), you just have less features. You need to pass a first date, a last date and a folder where to write the csv files.

The script which generates the data on https://traffic-viz.github.io/scenarios/covid19.html is `scripts/covid19_dataviz.py`. It's formatted with [jq](https://stedolan.github.io/jq/) before being pushed to avoid large diffs in the repository.
