### ISSUE TITLE
Not sure if EHS is not working or I am doing something the wrong way

### ISSUE THREAD

**Issue by richardalligier** [xoolive/traffic#85]
Hello,

I evaluated the code below taken from documentation
```
from traffic.data.samples import belevingsvlucht

df = opensky.extended(
    belevingsvlucht.start,
    belevingsvlucht.stop,
    icao24=belevingsvlucht.icao24
)

enriched = belevingsvlucht.query_ehs(df)
```

I get this warning ``WARNING:root:No data on Impala for flight TRA051.`` I do not see any EHS fields in `enriched.data`, just the usual fields.

Otherwise, classic opensky queries seem to work, the opensky authentication is working.

Did i make a mistake? Maybe the EHS fields are not stored in the `.data` attribute?

Thanks for the help,
Richard

**Comment by xoolive** [comment]
Indeed, I have to take a new example for the documentation. It seems they (OpenSky) had to save some disk space and removed some older data in this table...

`Flight.query_ehs()` should work with any flight in 2019 (the `df` parameter is only useful if you have a very large number of flights to decode), try a flight around Maastricht ACC just to be sure to get a lot of EHS data.

**Comment by richardalligier** [comment]
Yeah seems to work with Maastricht flights, thanks Xavier !
