### ISSUE TITLE
Number of aircraft crossed a sector

### ISSUE THREAD

**Issue by ClaudiusBZ** [xoolive/traffic#87]
I am currently trying to determine the number of aircraft in an ATC sector. For this I use the AIRAC cycle of Eurocontrol. Retrieving whole trajectories within a polygon works fine, but I would like to speed up this process and only determine the number of aircraft. Is such a method implemented, maybe I missed it in the documentation?

**Comment by xoolive** [comment]
A simple way to count trajectories intersecting an airspace is:

```python
sum(1 for flight in t if flight.intersects(airspace))
```

**Comment by ClaudiusBZ** [comment]
Many thanks for the suggestion. But I would have to download the trajectories first, which I would like to avoid.
After analysis of the SQL query, which is created by `opensky.history`, are the min and max values of the geographical extent inserted into the query when using `bounds` with an airspace shape? Doesn't the original shape of the airspace get lost?
The initial question also aimed to find out whether a function exists for the following syntax:

`SELECT COUNT(DISTINCT icao24) FROM state_vectors_data4 WHERE lat<=50.07 AND lat>=49.98 AND lon<=8.62 AND lon>=8.48 AND hour=1493892000;`

(Source: OpenSky example - [https://opensky-network.org/data/impala](url))

**Comment by xoolive** [comment]
Indeed, the request is made on the bounding box of the airspace. There are no geometry queries available with Impala, unlike postgis extension for postgresql.

The method to create custom queries is [`opensky.request()`](https://traffic-viz.github.io/opensky_impala.html#custom-requests) The documentation misses some examples and should be improved in the future.
