### ISSUE TITLE
add new custom column to trajectory dataframe

### ISSUE THREAD

**Issue by xoolive** [xoolive/traffic#88]
by @ClaudiusBZ

I have a problem to add new columns within an iteration. Maybe I do not understand the traffic class correctly. Within the iteration loop the custom operations are implemented correctly (a printed Dataframe is correct), but you can't see any change in traffic structure after the loop is finished. I use the iteration syntax you suggested in #81 with a custom function instead of aligned_on_ils.
Maybe you have an idea what is wrong here?

**Comment by xoolive** [comment]
Hello @ClaudiusBZ

Would you have a faulty sample code snippet? I don't really know what to say now except that "it should work"

**Comment by ClaudiusBZ** [comment]
I think I found a solution (my fault) so far. Here is the working example code:

```
from traffic.data.samples import dreamliner_airfrance

def add_column(row):
    return row['altitude'] * 2

tfc_ls = []

for flight in dreamliner_airfrance:
    altitude_2 = flight.data.apply(add_column, axis = 1)
    flight = flight.assign(altitude_check = altitude_2)
    check_ls.append(flight)

tfc_air_france = sum(check_ls)
```

My mistake seemed to be the `assign` method, I thought it changes the DataFrames of the individual flights in the traffic structure and the variable name is preserved. The creation of a new traffic structure from the processed data was not conscious to me so far.

**Comment by xoolive** [comment]
For your example, why not just do the assign on the Traffic structure:
```python
dreamliner_airfrance.assign(altitude_2=lambda df: 2*df.altitude)
```

Basically, `.assign(yyy)` just does `Traffic/Flight(xxx.data.assign(yyy))`. It's similar with many common pandas method, see [here](https://github.com/xoolive/traffic/blob/efee53377ad93ca9ce45b69923f3e4b08afd5656/traffic/core/mixins.py#L161). When these methods have an `inline` parameter, you can pass it as well if that's what you want (though doing that way, you miss the idea of chaining pandas structures)
