### ISSUE TITLE
covid19_dataset - aircraft.opensky_db; merge failes

### ISSUE THREAD

**Issue by RunningCarla** [xoolive/traffic#96]
Hi Xavier,

because of my master thesis I fortunately came across your excellent traffic python library and and have already used many of your really helpful methods for ADS-B data. 

Since a few days I try to rerun the covid19_dataset for certain flights. Unfortunately I have problems with merging the dataframes. In Debug Mode the dataframes are valid and not empty, but I get the error message when it comes to merge:
"a {obj} was passed".format(obj=type(obj)) - TypeError: Can only merge Series or DataFrame objects, a <class 'NoneType'> was passed

I already checked the paramiko connection ("INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.6p1) - INFO:paramiko.transport:Authentication (password) successful!")
The problem is obviously due to the "Flight database from Jannis" which is defined as none type, but unfortunately we don't know how to solve this issue. 

Can you help us or do we overlook another big mistake? 

Thank you very much in advance,
Carla

**Comment by RunningCarla** [comment]
Sorry for providing unnecessary trouble. The problem is solved now and the code runs without the database of Jannis. Error messages regarding paramiko still occur, but this does not prevent to get the necessary data. 
Thank you very much and apologies again!

**Comment by xoolive** [comment]
Thank you Carla for your comment. I am not sure I really get what bugged you but if you find a way to improve the documentation that would have helped, please feel free to mention it or to submit it in a pull request. This kind of feedback is helpful too.
